### ISSUE TITLE
Multiple MPD modules: second one controls wrong server

### ISSUE THREAD

**Issue by ghost** [polybar/polybar#1172]
I have a local MPD server and one on the internet and added modules for both of them, like this:
```ini
[bar/mybar]
modules-left = mpd-local mpd-online

[module/mpd-local]
type = internal/mpd

; I didn't expect this to change anything but tried with and without this anyway, no change:
host = localhost
port = 6600

format-online = local <toggle> <label-song>
icon-play     = ⏵
icon-pause    = ⏸
label-song    = %title%

[module/mpd-online]
type = internal/mpd

host     = mpd.example.org
port     = 1234
password = example

format-online = online <toggle> <label-song>
icon-play     = ⏵
icon-pause    = ⏸
label-song    = %title%
```

The first module works fine. The second one however acts up weird:

1. Initial state:  
![both players are paused](https://user-images.githubusercontent.com/4283376/38867324-3d9d2dca-4233-11e8-99fc-d66452db31c2.png)

2. Click the play button for the **online** player:  
![the local player started playing, the online one is still paused](https://user-images.githubusercontent.com/4283376/38867331-41daa02a-4233-11e8-86f0-b4337322bec2.png)  
The wrong one starts playing. It's indeed the local server that started producing sound.

3. Click the same button again:  
![both the online and the local player are now playing](https://user-images.githubusercontent.com/4283376/38867332-41fe5f4c-4233-11e8-9120-b95031c00383.png)

4. And again:  
![the local player is now paused, the online one is playing](https://user-images.githubusercontent.com/4283376/38867472-afc3e61e-4233-11e8-9b69-2a21c2712143.png)

5. Once more pauses the online server:  
![we're back to the initial state: both players are paused](https://user-images.githubusercontent.com/4283376/38867324-3d9d2dca-4233-11e8-99fc-d66452db31c2.png)

**Comment by NBonaparte** [comment]
If you have only the second one running, does it work normally?

**Comment by patrick96** [comment]
I was afraid of this. For modules with custom buttons (that don't execute a shell command), like the mpd, backlight, volume and even the date module, polybar sends an internal command on each button click. The problem: from the command itself you can only determine from which module type it came from not from which exact module (if you have more than one of the same type). Having more than one module of the same type can cause the modules to interfere with eachother, because the commands are generally handled by the first module that can handle them. So having two date modules will cause only the first one to toggle its label, even if you click on the second one.

In your case the first module first handles the `mpdpause` command from the online module, the next `mpdpause` command from the online module isn't handled by the local module, because it is already paused, so the online module handles it. The last two steps are analogous, just with the `mpdplay` command.

I don't think, there is a quick way to fix this, we'll need to do some work on how events are handled.
For now, unfortunately, you have to avoid having two mpd modules on the same bar.

@NBonaparte I really don't like how input events are handled right now, where for each input event (command or polybar internal commands) we loop through all modules and see if any of them can handle the event. We conflate shell commands and polybar commands, which I don't think we should. For simplicity, I think we should still use the `%{A}` tags for internal commands as well but we should prefix them with something so that it can never be mistaken for a command (e.g. `#`). Also modules should register a unique prefix so that all commands with that prefix go to that module. For example we use the name of the module (not the type but the name in the config), so the mpd commands could look like this: `#mympdmodule_play`, where the mpd module was defined as `[module/mympdmodule]`. This would fix this issue and also clean up a lot of the mess with modules having to handle and check for their own event prefixes (which are hardcoded into each full event name separately) themselves. What do you think?

**Comment by NBonaparte** [comment]
Seems a bit long if we used the module name, perhaps we could have an indexing system instead (`mpd0`, `mpd1`, etc.)

**Comment by M1dgard** [comment]
> If you have only the second one running, does it work normally?

Yes. If I remove `mpd-local` from `modules-left`, it works normally.

**Comment by rosenpin** [comment]
I seem to experience the same issue when using 2 pulseaudio modules, clicking or scrolling on either of them only affects one 
![image](https://user-images.githubusercontent.com/5289630/77227004-36a7a400-6b85-11ea-9a10-401bc9c4a686.png)
So if I scroll on my PC volume it still just affects the headphones one

Seems like it might be related to this issue, is there any progress regarding this issue?

**Comment by patrick96** [comment]
@rosenpin That is definitely the same issue. It affects all modules that have built-in click actions: https://github.com/polybar/polybar/wiki/Known-Issues#with-multiple-modules-of-the-same-type-actions-on-those-modules-control-the-leftmost-module

As far as I can tell, the leftmost module should always be the one that is triggered.

I have a work in progress PR at #1907 but I haven't had time to finish it. It's going to be a lot of work since there is a fundamental flaw in how we have been passing messages to modules, so this fix will involve changing how each and every module handles messages.

**Comment by rosenpin** [comment]
Thanks, I understand.  
Sounds like a bummer, I'll look into it if I get a chance :)

**Comment by ksoltysik** [comment]
Hey, is there any progress on this? This is pretty big modular design flaw when one cannot realistically have 2 modules of the same type next to each other, and unfortunately, a deal breaker for many (including me) who would like to use the polybar.

**Comment by ksoltysik** [comment]
Had time to test it for a day on Arch Linux, packaged by myself based on polybar-git. For what it's worth, it mostly works for `internal/pulseaudio` but when my sink is missing (disconnected bt headphones) I still get the old behavior.

**Comment by patrick96** [comment]
> For what it's worth, it mostly works for internal/pulseaudio but when my sink is missing (disconnected bt headphones) I still get the old behavior.

@ksoltysik Do you have a config for this? The patch should only deliver the new action names to the module with the same name.
