### ISSUE TITLE
Toggle margin on tray display

### ISSUE THREAD

**Issue by ghost** [polybar/polybar#1207]
Right now I'm forced to set padding-right = 0 on my bar to keep the spacing the same but as soon as the tray icon is gone for whatever reason there is this inconsistency in spacing:

![image](https://user-images.githubusercontent.com/11262717/39530497-5fb164e2-4e29-11e8-9782-3d2e4eaf1a8a.png)

![image](https://user-images.githubusercontent.com/11262717/39530383-231b9a7a-4e29-11e8-9592-4ce3ad6a8e7c.png)

I don't know if there is a workaround right now but I'd like to request an option to toggle a specific behavior when there is nothing in the tray area

**Comment by patrick96** [comment]
What do you mean by inconsistency? Are those two bars created from the exact same config? Why can't you set `padding-right` to anything else than 0?

**Comment by leewdch** [comment]
I think I might have used the wrong word but if I hide a margin there is an additional space between the modules and the tray area. I would rather have the same space that modules use.No matter what padding or margin I use with the tray anyway since it is not going to shrink more so I have to use margin 0 on the right modules

**Comment by patrick96** [comment]
What exactly is the problem with setting `padding-right` to something greater than 0? Is the additional space really that noticeable?

**Comment by gavsiu** [comment]
Can't the tray also have tray-margin like module-margin? Because without tray-margin, it butts up against a module when it shouldn't.

**Comment by odiferousmint** [comment]
Bump. I may have OCD and that is the reason, but that extra space is very noticeable. I tried floats but that did not work. I wish there was `tray-margin-left` and `tray-margin-right` as well.

**Comment by patrick96** [comment]
In the next release, the tray will be a module as well (see #2689) and things like `format-margin` to add space before and/or after the tray will work (I think that's what you want @gavsiu).

I think though the underlying issue is that `tray-padding` is also applied around the entire tray and there is no way to only control spacing between the individual icons. I think we'll overhaul some of the formatting in the tray module to fix this.

**Comment by patrick96** [comment]
@odiferousmint By the way, you can specify a pixel value for `label-margin-right` (at least starting with polybar 3.6). For example `label-margin-right = 20px`. Of course this doesn't protect you from the number of tray icons changing.

**Comment by odiferousmint** [comment]
> @odiferousmint By the way, you can specify a pixel value for `label-margin-right` (at least starting with polybar 3.6). For example `label-margin-right = 20px`. Of course this doesn't protect you from the number of tray icons changing.

Thank you, I did not know that!

**Comment by gavsiu** [comment]
> In the next release, the tray will be a module as well (see #2689) and things like `format-margin` to add space before and/or after the tray will work (I think that's what you want @gavsiu).
> 
> I think though the underlying issue is that `tray-padding` is also applied around the entire tray and there is no way to only control spacing between the individual icons. I think we'll overhaul some of the formatting in the tray module to fix this.

That's great news. I read through https://github.com/polybar/polybar/issues/2689 and can't wait. Thanks.

**Comment by patrick96** [comment]
The new tray module now has better handling for margin and padding
