### ISSUE TITLE
Bar itself shifting to right

### ISSUE THREAD

**Issue by l7ssha** [polybar/polybar#1268]
Hello, my bar sometimes shifts all contents to right, that clock isn't visible. It's very irritating. 
This is my fault or internal bug?

![image](https://user-images.githubusercontent.com/23033957/40855993-7e26e356-65d6-11e8-84b2-29f8eca73bc7.png)

Polybar config: [in my repo](https://github.com/l7ssha/dotfiles/blob/master/config/polybar/config)
Polybar version: `polybar 3.1.0-git`
OS: Arch Linux, 4.16.9-1-ARCH, Openbox WM

**Comment by patrick96** [comment]
If you have too much text on your bar, polybar can't render all of it because there just isn't enough space. I would suggest fewer or less verbose modules. Also you say that it only happens sometimes, so you seem to have a module that frequently changes the amount of text it displays, causing everything to shift and completely fill up the bar.

**Comment by l7ssha** [comment]
But there is almost twice space available to fill up.

When first module from left indicates "0 kb/s 0 kb/s" bar is shifted, and when module displays 3 digit numbers bar is working correctly.

Resolution: 1920x1080

![image](https://user-images.githubusercontent.com/23033957/40878638-ef7c1da6-6693-11e8-920a-fc5c7d10fea5.png)

**Comment by l7ssha** [comment]
There is logfile.

[polybar-log.txt](https://github.com/jaagr/polybar/files/2065765/polybar-log.txt)

**Comment by patrick96** [comment]
Hmm, I am unable to reproduce this (also on 1920x1080). I tried to use your exact config (with hardware names changed for my machine) and also piped the output you provided into polybar directly and let it display that, and both do not, ever, make the bar shift to the right.

Does this happen with other configs as well? When you remove the network module, does this also happen? Does it also happen, when you use the built-in network module?

Can you please run polybar with `-l trace` and also post that output here.

**Comment by l7ssha** [comment]
When I remove this module it works like expected. But in my case it's only script.

I can't get working `polybar -l trace`. It's outputs
```
error: Trace logging is not enabled...
```
I don't know what it means in my case.

**Comment by patrick96** [comment]
> error: Trace logging is not enabled...

Ah yes this isn't enabled by default in 3.1.0, can you instead run it with `-l info`.

> But in my case it's only script.

So that means, if you use the internal network module, this doesn't happen?

**Comment by l7ssha** [comment]
Command output:
[polybar-info.txt](https://github.com/jaagr/polybar/files/2066118/polybar-info.txt)

**Comment by patrick96** [comment]
Nothing looks out of the ordinary in the logs.
I am really not able to reproduce this, even on Arch and Openbox.
But this looks like a bug to me and a really elusive one it seems.

Because I can't test this myself and thus can't track down the issue alone, I'll ask you a couple of questions about your setup:
1. How many monitors do you have connected?
2. Do you have any xorg related software for which you have held back updates on purpose?
3. Does this issue still happen, when you move the netspeed module to `modules-left`?
4. Does this issue still happen, when you move the netspeed module to `modules-center`?
3. Does this issue still happen, when you move the netspeed module to any other position in `modules-right`?

**Comment by l7ssha** [comment]
1. One monitor 1920x1080, second 1366x768
2. I don't think so
3. Nope
4. No
5. No

Basically today i didn't observe this bug. This has some very weird behavior. For now I'm leaving this at different position on `modules-right` and I'll observe it and post feedback.

**Comment by patrick96** [comment]
Alright, it seems weird to me that such a custom script module would cause this. Maybe it has to do with the interaction of the modules or something like that.

**Comment by patrick96** [comment]
@l7ssha Are you still experiencing this bug regularly? I may have found the issue and written a fix for it in #1936 but since I was never able to reproduce this, I can't say for certain that it fixed this issue.

If you could, please try out the PR I linked and let us know if you no longer experience that issue.

**Comment by l7ssha** [comment]
Not really, seems right now. I think it was rare, environment specific bug, which indeed was hard to reproduce. Thanks for your work
