### ISSUE TITLE
stacked text

### ISSUE THREAD

**Issue by mcginty** [polybar/polybar#1363]
It'd be a great feature to support stacked (multi-row) text formatting. It'd be great in places like the "network" module to render the up/down speed, for example.

That is,
```
2 KB/s / 100 KB/s
```

could turn into

```
2 KB/s
100 KB/s
```

**Comment by patrick96** [comment]
Would there be any other use case, besides having up and down-speeds on different lines?

**Comment by unai-ndz** [comment]
This could allow to make vertical bars, depending on how it's implemented. A use case for that will be [this](https://redd.it/92guq6), but less hacky and using several rows for modules.

**Comment by mcginty** [comment]
@patrick96 At least for me, up/down speeds are the most obvious use case (not just for network, but disk I/O, etc.). I can also imagine it being useful for other random things like stocks/currency tickers (symbol + price), etc., depending on what type of numbers float your boat.

**Comment by patrick96** [comment]
Vertical bars are already on our to-do list, but it's probably going to be a while.

While the link you posted @unai-ndz looks really neat, you won't be able to do this, even if you had a bar with multiple rows.

I don't think we're going to implement this, because it would look really weird, if you had a bar with two rows but the second row was empty except for the few places where you would actually use this feature.

**Comment by mcginty** [comment]
@patrick96 the way I was imagining, the stacked text would be half-sized, so that it would fit in the same height-space as a single row of text, it would just be smaller. Every other status bar that implements this feature does it that way, and it looks quite normal.

**Comment by patrick96** [comment]
Ah, I see. As far as I can tell there is no way to set the font size to an arbitrary value for all fonts. @NBonaparte do you know, if there is a way to scale the textblock after it was rendered?

**Comment by NBonaparte** [comment]
It probably can be done through Cairo, but scaling text isn't optimal compared to just rendering them at a smaller size.

**Comment by mcginty** [comment]
Sure, these types of bar items are pretty common coming from macOS-land at least:
 
![monitor-system-usage-stats-your-mac-os-x-menu-bar 1280x600](https://user-images.githubusercontent.com/373823/44989785-806a7280-af7e-11e8-88f7-3df6e4486819.jpg)

**Comment by mcginty** [comment]
I decided to get real hacky and make my own prototype using 3 instances of polybar. Here's a screenshot to show how it might look within polybar.

![2018-09-16-221309_2560x1440_scrot](https://user-images.githubusercontent.com/373823/45747967-af801580-bc07-11e8-9296-157fbd15a7ef.png)

**Comment by patrick96** [comment]
It's still closed because I have not looked at this issue since.

I must admit your example does look quite good.

I'm not totally averse to having this feature as long it doesn't require us to tear up the entire code base. For a feature like this, changes would need to be made along the whole pipeline of config values, producing formatting tags, parsing, and rendering.
The main issue I see here is that not all fonts support rendering at arbitrary sizes (I think bitmap fonts don't support that). This would either require rendering both rows full size and scaling down or forcing the use of an arbitrarily scalable font in those stacked environments.

If someone want's to actively work on this, I'm all for it, I don't think anyone on the polybar team will have time to implement this in the next months at least (there is lots of stuff with higher priority). It's probably best if they first propose how this would be represented in the config as well as with formatting tags and how rendering would be done.

If any of you want to tackle this, announce it here and I'll reopen the issue.

**Comment by hoshiya4522** [comment]
Does polybar now support vertical bars?

**Comment by joshpetit** [comment]
Doesn't look like this issue has gotten attention, are there work arounds people have been using to accomplish this?

**Comment by patrick96** [comment]
There has not been any efforts in this direction that I am aware of. I have also decided that this feature is out-of-scope for polybar.
