### ISSUE TITLE
Tag parsing not taking multiple tags in the same block

### ISSUE THREAD

**Issue by Phaenyxx** [polybar/polybar#1555]
Hi, when setting the foreground / underline colors with tags in ramp-capacity, I noticed the underline and text color goes unchanged until something else (in this case, my exit module) changes it. 
Do you have any idea of is this is normal / a bug ? 

**Normal functionment (without Tag editing):**
![image](https://user-images.githubusercontent.com/27176415/50425256-fd459300-0872-11e9-958a-4e26533295ae.png)
**Bugged functionment (with tag editing):**
![image](https://user-images.githubusercontent.com/27176415/50425268-28c87d80-0873-11e9-85e1-b2e38f399a6f.png)

```
[module/battery]
type = internal/battery
full-at = 95
battery = BAT0
adapter = AC
poll-interval = 5
format-charging = <animation-charging> <label-charging>
format-charging-foreground = ${colors.green}
format-charging-underline = ${colors.green}
format-discharging = <ramp-capacity> <label-discharging>
label-charging = "%percentage%%  "
label-discharging = "%percentage:2%%  "
label-full = 
ramp-capacity-0 ="%{F#bf616a u#bf616a +u}   %{-u}"
ramp-capacity-1 ="%{F#d08770 u#d08770 +u}   %{-u}"
ramp-capacity-2 ="%{F#ebcb8b u#ebcb8b +u}   %{-u}"
ramp-capacity-3 ="%{F#a3be8c u#a3be8c +u}   %{-u}"
ramp-capacity-4 ="%{F#a3be8c u#a3be8c +u}   %{-u}"
animation-charging-0 = "   "
animation-charging-1 = "   "
animation-charging-2 = "   "
animation-charging-3 = "   "
animation-charging-4 = "   "
animation-charging-framerate = 500
```

## Environment:
* WM: i3-gaps
* Output of `polybar -vvv`:
```polybar 3.2.0-73-gbc9eddf

Features: +alsa +curl +i3 +mpd -network(wireless-tools) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/clang++
Compiler flags:  -Wall -Wextra -Werror -pedantic -pedantic-errors -Wno-error=parentheses-equality -Wno-zero-length-array
Linker flags: ```

**Comment by patrick96** [comment]
This certainly isn't expected behavior. After a bunch of digging it seems that polybar doesn't fully support multiple formatting tags in a single formatting block in raw tags in your config:
```
%{F#bf616a u#bf616a +u}
```

I consider this a bug since lemonbar supports that and polybar should support the lemonbar syntax.

You can fix the issue on your side by using a formatting block for each tag:
```
%{F#bf616a}%{u#bf616a}%{+u}
```

Btw, each level of the ramp can be styled like any label, so you could also set 
```dosini
ramp-capacity-0-underline = #bf616a
```

**Detailed Explanation:**

If raw tags are given, polybar parses those in the builder before it generates the final string that is passed to the actual parser and renderer. It does that mainly to be able to close all formatting tags that were opened inside the raw tags. The parser doesn't take into account that multiple formatting tags can appear inside the same block, so when it encounters `%{F#bf616a u#bf616a +u}`, it parses this as "set the text color to `#bf616a u#bf616a +u`". Because of this it doesn't parse the `u#bf616a` and `+u` part. When it then encounters `%{-u}`, it discards it because it thinks that the underline was never activated (even though it was). In the final output that is passed to the parser `%{-u}` is missing and thus the underline continues on until it reaches the next module.

**Comment by Phaenyxx** [comment]
Ok, I get it. Thanks for the explanation. Turned out I was also doing the wrong thing : I wanted the underline / color to go through the ``<label-discharging>`` as well, so I symply put the ``%{-u}`` and ``%{F-}`` at the end of the label. Everything works like a charm now.

**Comment by patrick96** [comment]
I'll leave this open, as it's still a bug

**Comment by Phaenyxx** [comment]
Of course, I'm sry, new to github and issues. Anyway, have a great day !
