### ISSUE TITLE
Allow `px` units when specified

### ISSUE THREAD

**Issue by Navigatron** [polybar/polybar#1651]
I find it difficult to achieve the look I desire when the only unit available is spaces.

For example:  
`label-unfocused-padding = 0`  
`label-unfocused-padding = 1`

0 is much too small. 1, while tolerable, is just a little too big.

In addition, this spacing will change in size with the font size. Sometimes this is great - other times I would rather it not.

Ideally, adding the `px` extension to a number would cause that number to be treated as pixels instead of spaces.

- This allows greater control for those that want it
- This does not break existing configs, like #204 

I am currently using formatting tags in labels to work around this.

**Comment by MyNameIsCosmo** [comment]
+1

I currently use `label-separator = &nsbp;` (replacing &nsbp; with an actual non-breaking space) to get separation between labels, since I can't have half-padding values (or change the padding character/size)

If `px` is not a preferred method, perhaps we can change the font-size or character of the padding character?
https://github.com/jaagr/polybar/blob/a0b888b5e6fa81422d05ff7c571e3b0c3871e901/src/components/builder.cpp#L299-L308
https://github.com/jaagr/polybar/blob/ea5fc22c7d43d7f4d25855124b275159f43c3371/src/modules/bspwm.cpp#L409-L411

**Comment by patrick96** [comment]
At first sight this doesn't seem *too* difficult. We could directly also support other types like points (1/72 inch). This would help address #951.

I'll list the things that I think would need to be done.

1. We need to be able to parse these values and represent them. Parsing should be easy, I think it could be done inside `config.hpp` and the representation could be:
```cpp
enum size_type { SPACE, POINT, PIXEL };

struct size {
  enum size_type type;
  size_t value;
}
```

2. We need to use this representation throughout polybar when it comes to spacing. @MyNameIsCosmo already mentioned some code locations for this. For one `builder::space` should now accept `struct size`.

3. Wherever spaces are produced now the `%{O}` formatting tag should be emitted for spacing based on pixels and spaces should still be used if `size_type::SPACE` is used. I think we would only need to change `builder::space` here but there could be other places that produce spaces for spacing.

4. One issue here is about where we want to translate points to pixels with the dpi set in the bar config. I'm not sure the config should actually know about `dpi` and just do the parsing (separation of responsibility). If `builder::space` is truly the only place that handles spacing, we could just do the translation there.

5. Set the dpi inside `bar_settings`. This just involves moving the relevant code from `renderer.cpp` to `bar.cpp` and accessing `dpi_x` and `dpi_y` through `m_bar` inside `renderer.cpp`. This is needed so that wherever we do the translation from points to pixels, we have access to the dpi settings.

This has turned more into a breakdown of what needs to be done to support a DPI-dependent unit like `pt` instead of `px`, but I think we can implement both at the same time. 

Ideally we can find a way that can help solve this as well as the issue in #951 at the same time without too much code duplication. The main challenge is that for `width` and `height` a unit like spacing does not make sense while a percentage does. Also we don't use `builder::space` for `width` and `height`.

If anyone wants to take a crack at this, I think we could start with just implementing the functionality for pixels, for this we would only need points 1-3 and could drop `POINT` from 1.

**Comment by Lomadriel** [comment]
I would like to help on this feature, however I don't see exactly how do you want to print the space.
Do you want to convert pixel to space or do you want to change the way the "space type" are managed into the builder::space?

I already started to adapt the code and the ```config``` class to use the struct rather than an int.
