### ISSUE TITLE
Change branching and versioning model

### ISSUE THREAD

**Issue by Ovsyanka** [polybar/polybar#1780]
In short words I suggest changing the branching model to the [git-flow](https://nvie.com/posts/a-successful-git-branching-model/).

## Main problems with the current workflow

* Development packages always has lesser version compared to the current release. It is really confusing and not reflect the reality.
* The repository has hanging release branches and it is bad at least because you can't be sure that all hanging branch changes exists in the development branch.

## The solution

I suggest to use git-flow model because it doesn't have this drawbacks and suits to the project quite well. It is commonly used and lot of developers is familiar with it (it is my own opinion, maybe I am wrong).

The only problem I aware of by now is that you will have conflicts in the version.txt file while merging release branches. And this problem is solvable in few different ways. The main approaches I see:

1. Do not store version info in the source code itself. It can be determined by branch|tag name on the building stage. And the version.txt file can be created and added to the release file if needed.
2. You can leave version.txt file in the source code and add custom merge strategy for that file to leave it content unchanged on a merge (as it is in the current branch).

I can handle both of the approaches, you just have to peek one.

## Your opinion

I am looking for your opinion about:

* Do you agree that git-flow is an appropriate model? If it is not - why?
* Which version conflicts handling approach do you prefer?

**Comment by patrick96** [comment]
Hi Igor.

Thanks for writing this down after we discussed it on IRC.

> Development packages always has lesser version compared to the current release. It is really confusing and not reflect the reality.

To clarify, this is talking about the `polybar-git` package.

I also don't really like the hanging release branches, though we make sure that we alway cherry-pick from `master`, this way we can be sure that master contains all changes from release branches.

I would like to know how git-flow fixes the versioning issue? The `polybar-git` package should contain the latest commits on the develop branch (referencing the `develop` branch from [this git flow description](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)). If we create a patch release, say version 3.3.2, how could we get the `polybar-git` package to have a higher version number than that if the `3.3.2` tag won't be on the `develop` branch?

I think deleting `version.txt` would make sense, and we should then write a script to create a release archive where the `version.txt` is created from git.

git flow seems to me a bit too complicated for this project because it involves merging changes into multiple branches (`master` and `develop`) sometimes which doesn't really fit with the PR model here on github. Do you have experience with git flow on github? I would be interested to hear your perspective.

Unfortunately now *I* am going away for a few days, so I'll only be able to get back to you after the weekend.

**Comment by Ovsyanka** [comment]
> I would like to know how git-flow fixes the versioning issue?

Actually in the first place I suggested git-flow to fix hanging branches. In matter of versioning issues I just described it could be fixed in that flow.

> I think deleting version.txt would make sense, and we should then write a script to create a release archive where the version.txt is created from git.

I agreed. The build script can use it if it exists and create if it is not.

> If we create a patch release, say version 3.3.2, how could we get the polybar-git package to have a higher version number than that if the 3.3.2 tag won't be on the develop branch?

I realized that in terms of git-flow it is more suitable to use `release` branch for the `-git` package instead of
`dev`. As I understand, in the current flow `-git` packages builds from the `master` branch and could be called as
upcoming release. In the git-flow upcoming release in the  `release` branch, not the `dev` branch.

According to that you will always know what is the current release.
* In the `prod` branch you always will have `v-x.x.x` tag.
* In the release branch you always will have `r-x.x` branch name. The version could be x.x.rx.hash (for example 3.4.r1.a17a017)
  according to the arch [guidline](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git) and it would be
  determined by commit number in that branch and it's id.
* In the `dev` you will not have version information because the particular version is't known yet. It could be MAJOR
  change or MINOR change and it will be determined on the release branch creating. This branch is only for the
  development and not for the publishing.

When the release considered ready to go into the production it should be merged into the `prod` branch and the version
would be like `3.4.0`.

So in the described case we will have:

* production branch with the `v3.3.2` tag
* release branch `r3.4` (or `r4.0`) with the next release
* development branch

In the release branch the build script will construct the version depending on the current commit and branch name:
`3.4.r15.fdlg87f` (or `4.0.r0.kdjfu76`).

> git flow seems to me a bit too complicated for this project because it involves merging changes into multiple branches (master and develop)

In my opinion it mostly haven't superfluous complicity. All it's "complicity" is just about making hidden processes visible. For example, when you make merge commit from the `release` branch to the `dev` (as git-flow says) - you tell for everyone that `dev` branch is up to date and has all changes from the `release` branch.

These multiple merges could be automated by [git-flow](https://github.com/nvie/gitflow) extension or others, there is a
number of such. I gonna choose later.

You may not use all the power of the git-flow. For example the development branch may be considered redundant in your
case, but I am not sure. It could be harder to adapt the flow then just have "empty" (I mean with only merging commits)
`dev` branch.

Of course you may try to develop another model, that fits your needs, but I think that it is a good idea to start from git-flow as
a basis and then adopt it (shrink or extend) if needed.

> sometimes which doesn't really fit with the PR model here on github.

Yes, look like multiple merges isn't common, but there is no principal problem with that. You can do it by hands and
that means it can be automated in some way.

> Do you have experience with git flow on github? I would be interested to hear your perspective.

No, I haven't yet. But I am quite confident that it could be used with some changes/additions and I believe I could
handle it. My confident based on the opinion that git-flow reflects actually going development processes quite well.

**Comment by patrick96** [comment]
So we discussed this internally a bit and I think it would be nice to use something like git-flow, but there are some issues to iron out because git-flow doesn't play nicely with the fork-PR workflow.

---

First of all, in the original [git flow blog post](https://nvie.com/posts/a-successful-git-branching-model/) the branches described are:

* `master`: Production ready branch with tagged releases
* `develop`: Where new features and non-critical bugfixes are merged into
* `release/*`: To prepare new releases (branches off of `develop`)
* `feature/*`, `bugfix/*`, `hotfix/*`

Right now we use our `master` branch in the way the blog post describes `develop`.
Though you can change the default branch on github all existing clones won't automatically check out the new default branch and existing contributors are likely to create PRs that branches off the production branch.
So in the rest of this post when referring to `master` I am referring what the blog post calls `develop` the branch where active development goes on. And when referring to `stable` I mean the production branch.

This will also make the migration easier since we can just create the `stable` branch from the last minor release and continue normally.

---

The problems we wanted to fix with a new release workflow were:

1. Hanging release branches
2. `polybar-git` having a lesser version compared to `polybar` when at least one patch release was published

Number 1 is solved automatically by git-flow.

Number 2 is solvable and quite elegantly even. The original describes publishing a new release as follows:

1. `git checkout -b release/VERSION master`
2. Bump version and commit
3. `git checkout stable`
4. `git merge --no-ff release/VERSION`
5. `git tag -a VERSION`
6. `git checkout master`
7. `git merge --no-ff release/VERSION`

With this approach there is no version information available in `master` since the version tag is on the merge commit `Merge branch 'release/VERSION' into stable`.

But the [`gitflow`](https://github.com/nvie/gitflow) git extension by the same author as the original blog uses a slightly different approach. In the last step they actually do `git merge VERSION`, they merge the tag into `master`. With this we actually do have version information on `master` and even better it will always have the version information for the most recent release (not only minor releases as we do right now). So `polybar-git` could use that version information to create the version string as it has done before (we wouldn't even have to modify the `PKGBUILD`).

This approach of merging the tag into `master` will also merge the merge commit for `stable` into `master`. We could then actually use the merge commit as our release commit with the changelog and everything.

---

We will probably only need a subset of git flow, so I'm going to quickly go over what we need and don't need and what we have to change.

`feature/*` `bugfix/*` `support/*` branches are not really needed since we don't directly push to `origin`. Contributors can still choose to use these naming conventions but it's up to them. When merging we will continue to use the current approach of squashing or rebasing. The biggest advantage of `--no-ff` merge is that you can easily undo entire features, but github already provides functionality to revert entire PRs so that shouldn't be necessary. 

The process for creating a new release stays largely the same. But I want to keep the release branches short lived, ideally they are merged after a few days. This way we can have `polybar-git` point to `master` without it missing bugfixes that are only in the release branch for too long.  When merging a release we can follow the steps I listed above but with a few modifications:

* In step 5 we can probably do without an annotated tag since we create a release using github's release drafting tool anyway. We only use `git tag VERSION`
* In step 7 we should use `git merge --ff VERSION` (merging the tag *with* fast-forward if possible) to not clutter up m̀aster` with merge commits when it's not necessary.

If releases are merged before any other changes are made to `master` (which is quite likely) this won't even create a merge commit on `master`.

The biggest change is with hotfixes. Hotfixes are special since they need to be branched off `stable` and are the only way to create patch releases (e.g. `3.3.X`). Most contributors will branch off of `master` when creating any kind of code, even for hotfixes. So when a bugfix comes in via PR we the maintainers decide whether or not it is worthy of a hotfix and new release. If it is we create a hotfix branch from `stable` and cherry-pick the PR and then merge it as a hotfix. This process is largely the same as when merging a regular release.

That's about it. With these modifications the day-to-day operations with merging features and fixes stay the same, we only change how we create releases. I will also write down the exact procedure for new releases to replace our [Release Guidelines](https://github.com/polybar/polybar/wiki/Release-Guidelines) once we agreed that this approach works.

@Ovsyanka what do you think?

@Lomadriel I hope I have correctly articulated what we discussed, feel free to criticize.

---

### Tooling

We will likely need to write some custom tooling to make this process smoother. There is already a [`gitflow`](https://github.com/nvie/gitflow) git extension. But since we don't use many of the git-flow features and the release/hotfix branch is on a different remote than `master` and `stable`, I don't know how useful it would be. We also changed the process a
little, so it is probably best to create a script that merges release branches (steps 3-7 above). We may not even need a script and just write down the 4 commits needed in the documentation.

We also discussed removing the `version.txt` file from the repo. To do this we could create a script that automatically creates a release archive with the appropriate `version.txt` file. This wouldn't be too difficult to write and would also reduce the overhead for releasing new versions (`git ls-files --recurse-submodules` might prove useful`).

**Comment by Ovsyanka** [comment]
I think you made a great job about this question. In total it is not exactly what I assumed, but still this all looks sane to me at the first look. It always can be extended, so I think you should start with that.

I was confused by the sentence you used few times: "to merge the tag". But I figured out that you  meant apparently "merge the history with the tag" and then it has got meaning to me.

> In step 7 we should use git merge --ff VERSION (merging the tag with fast-forward if possible) to not clutter up m̀aster` with merge commits when it's not necessary.

The history could be messy in that case. I couldn't imagine any other serious drawbacks, so you can try and see how it will go.

About the tooling - In general I agree with you that the simple selfmaded script would be good choice for the start.
There is multiple tools to work with the git-flow (some of them have the capability to change the default branch namings), but you could just waste your time with choosing the right one and then your requirements will change and it becomes useless.
So, with the custon script If you will need some changes it will be simple to change. When the whole process will be settled down you could think again about using some existed tool that will fit into your process.

**Comment by patrick96** [comment]
So, I have decided that we will use [OneFlow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow) instead of GitFlow as our branching model. It has a lot less complexity and doesn't requires us to maintain a `stable` branch. Otherwise it is quite similar to GitFlow.

I am still working out exactly how we want to deal with hotfixes when the fix comes from a PR from an external contributor. Because, as in GitFlow, the hotfix branch must be branched off of the latest release tag.

**Comment by Ovsyanka** [comment]
> I am still working out exactly how we want to deal with hotfixes when the fix comes from a PR from an external contributor. Because, as in GitFlow, the hotfix branch must be branched off of the latest release tag.
@patrick96 

Honestly I don't see many options here. If someone doing his PR based on the wrong commit - you either ask the author to rebase his PR to the correct commit or do it by yourself. Maybe I don't completely understand the knot, though.

**Comment by patrick96** [comment]
Yes, those are also the options I am considering right now. 

Unfortunately a contributor can't really know what the right base commit is for a bugfix because it is up to the maintainers to decide which bugfixes should be put in a patch release and which should just be part of the next minor release.

Also, I am not sure whether rebasing will actually work. If they branched off `master` and then do `git rebase 3.5.1`, their PR would also include all the commits between version 3.5.1 and the commit on `master` they branched off of. I think they would actually need to branch off of the correct release tag and then cherry pick all the bugfix commits. This is of course doable, but probably a bit much for new or casual git users. We probably won't get around just cherry-picking the commits ourselves most of the time.

**Comment by Ovsyanka** [comment]
> Unfortunately a contributor can't really know what the right base commit is for a bugfix because it is up to the maintainers to decide which bugfixes should be put in a patch release and which should just be part of the next minor release.

Yes, but this is the general problem not related to chosen workflow. And I see the only way to solve it by some recommendations in the Contribution section about choosing the right starting point. It can involve optional communication with maintainers as the start. In general I would recommend something like "If you have doubts what starting point should be or if you think that it will be difficult to rebase on other base - ask contributors in gitter or in the related issue where should you start".

> Also, I am not sure whether rebasing will actually work. If they branched off master and then do git rebase 3.5.1, their PR would also include all the commits between version 3.5.1 and the commit on master they branched off of. I think they would actually need to branch off of the correct release tag and then cherry pick all the bugfix commits.

Yes, basically you are right, if PR branch will be rebased just with `rebase <branch>` it will have all these commits from master. And cherry-picking is the one of the correct approaches. But in my opinion it is more convenient to use the option [--onto](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---ontoltnewbasegt) in that case. The one just need to do `git rebase --onto <correctBase> <oldBase> <branch>`. For example, if someone started his PR `feature/issue1` from the `master` branch and he should rebase it on the `v-1.0.0` the command would be: `git rebase --onto v-1.0.0 master feature/issue1`. It will take all the commits `feature/issue1` branch has and `master` don't and apply them on top of the `v-1.0.0` commit.

**Comment by Ovsyanka** [comment]
> So, I have decided that we will use [OneFlow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow) instead of GitFlow as our branching model. It has a lot less complexity and doesn't requires us to maintain a `stable` branch. Otherwise it is quite similar to GitFlow.

It looks sane indeed. I think it is a great choice in case you support only one version at the same time. In fact I basically use it at work even without knowing about it.

Just to note, my personal rating of the finishing a feature branch strategies:
1. `Option #3 – rebase + merge –no–ff` - it is most clear solution, you can actually see distinct commits of different PRs.
2. `Option #1 – rebase` - not so clear, but okay.
3. `Option #2 – merge –no-ff` - I wouldn't use that bacause it would be messy history. The only reason I can imagine to use it is when you have conflicts in the same area in miltiple commits of your branch. But it shouldn't happen at the regular basis.

**Comment by patrick96** [comment]
I have never used rebase --onto myself (always just regular rebase), but it's perfect for this case. But yeah, we definitely need documentation that explains how people can decide where to branch off.

As for merging PRs (except for the ones that trigger a release), we will continue using the same strategy we always have, which is using GitHub's built-in merge buttons with merge commits disabled. So either squash or rebase and merge (`--ff-only`).
I'm not really a fan of merge commits and having one for every PR we merge is too much. For release branches (regular and patch) we will use `git merge --ff` so that when possible no merge commit is created (unlikely for patch release, but for most regular releases, no merge commit is required).
