### ISSUE TITLE
Scrolling/marquee text effect instead of truncating and ellipsis

### ISSUE THREAD

**Issue by unode** [polybar/polybar#1787]
Currently most polybar modules allow specifying a given number of characters to truncate long text, usually followed by ellipsis or some user specified character.

While this is ok, the truncation is often suboptimal hiding most of the relevant information. For instance in `mpd` this often means hiding the song name while showing the group/band name when using `%artist% %title%`.

A possibly better alternative would be some form of [marquee text](https://www.html.am/html-codes/marquees/css-marquee.cfm) which without truncation would allow reading the complete message.

This could also indirectly address #531 since truncation would no longer be necessary.

**Comment by Lomadriel** [comment]
> A possibly better alternative would be some form of [marquee text](https://www.html.am/html-codes/marquees/css-marquee.cfm) which without truncation would allow reading the complete message.

It might be a good idea but what would you suggest for the syntax in the configuration?

> This could also indirectly address #531 since truncation would no longer be necessary.

This still need to be fixed, we won't remove truncation since some users want to use this feature.

**Comment by unode** [comment]
> It might be a good idea but what would you suggest for the syntax in the configuration?

I'm not familiar with polybar's internals but here's a proposal:

```
GitHub: %{M:speed:length}%polybar_repo%%{M}
```
where:
- `speed` is how fast is rotates
- `length` how many characters to show
- only the part contained in `%{M}` would rotate.

e.g.:
```
GitHub: %{M:300:12}polybar/polybar %{M}
```
would become:
```
GitHub: polybar/poly
GitHub: olybar/polyb
GitHub: lybar/polyba
GitHub: ybar/polybar
GitHub: bar/polybar 
GitHub: ar/polybar p
GitHub: r/polybar po
GitHub: /polybar pol
(...)
```

The rotation could be done per character (easier, less visually pleasing, less cpu demanding) or per pixel (harder, smoother, more cpu hungry).

**Comment by patrick96** [comment]
With the current setup we have, this seems almost impossible. We would need to keep track of the current state of each marquee individually. We would also need to make sure that polybar rerenders its output at regular intervals now instead of on-demand. Now the first one may be doable by giving each marquee a unique ID and store the state tied to this ID. The second one is not possible without almost completely rethinking the renderer.

**Comment by unode** [comment]
For scripted modules there is the `tail = true` option.
If the marquee effect is delegated to the module, wouldn't this satisfy the 'regular updates' part?

**Comment by patrick96** [comment]
>  If the marquee effect is delegated to the module, wouldn't this satisfy the 'regular updates' part?

Not necessarily, not all modules are updated on regular intervals, many modules are event based and only update on new events (e.g. i3 module).
Also all module would need to update simultaneously otherwise it could be quite annoying when marquees move at the same speed but at different times.

I really don't see a way to implement marquee without tearing up almost all of the code.

**Comment by unode** [comment]
Ok, thanks for the insight and feasibility assessment.

Your call on closing here or leaving it up for a future major version of polybar or future major rewrite.

**Comment by patrick96** [comment]
I'll close this to not clutter up the issue list but we'll keep it in mind for any future major rewrite.
