### ISSUE TITLE
"Systray selection already managed" when running the same bar on 2 monitors

### ISSUE THREAD

**Issue by marioortizmanero** [polybar/polybar#1796]
## Describe the issue
i3 is currently unable to run 2 systrays, which is important on multiple monitor setups. My current configuration for the tray icons is:

```
tray-position = right
tray-padding = 2
tray-background = ${colors.background}
tray-reparent = true
```

This throws these 2 lines as an error or warning:

```
error: tray: Failed to put tray above 0x1200001 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x0a00005)
```

And proceeds to randomly show the systray on one of the 2 bars:
![Image](https://i.imgur.com/WoWuzbi.png)

**Expected behavior:**

Polybar should be able to run the systray in 2 or more bars.

*What actually happens*

Polybar only shows the systray in one of the bars, randomly.

**Was it working before?**

I think I've seen the systray on my 2 monitors sometime but I don't know what I did.

## To Reproduce
Here's my launch script:

```bash
MONITOR=HDMI-A-0 polybar --reload status_bar &
MONITOR=DVI-D-0 polybar --reload status_bar &
polybar status_bar
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
error: tray: Failed to put tray above 0x1200001 in the stack (XCB_MATCH (8))
warn: Systray selection already managed (window=0x0a00005)
```

## Environment:
* WM: i3 version 4.16.1 (2019-01-27)
* Distro: Arch Linux x86_64
* Output of `polybar -vvv`:
```
polybar 3.3.1

Features: +alsa +curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

```

**Comment by patrick96** [comment]
This is normal behavior. I have never seen *any* tray implementation that can display the tray multiple times. The issue is that you basically "register" yourself as a tray manager and there can only be one of those per X session, that's why you get that error.

What you are trying to do is AFAIK not possible, the bar that first "registers", will display the tray, the other will fail. If you at least want to always have the tray on the same monitor, I suggest using another env variable for `tray-pos`:

```dosini
tray-pos = ${env:TRAY_POS:none}
```

```bash
MONITOR=HDMI-A-0 polybar --reload status_bar &
MONITOR=DVI-D-0 polybar --reload status_bar &
TRAY_POS=right polybar status_bar
```

**Comment by marioortizmanero** [comment]
KDE is able to do so. Isn't there a workaround or something similar?

**Comment by patrick96** [comment]
> KDE is able to do so. Isn't there a workaround or something similar?

I see. No there is no workaround. KDE has the ability to display the tray multiple times either because they use a different protocol to manage the tray or because they have one central tray manager that replicates the tray at different places. With polybar, since eath bar is its own process and they don't communicate with each other, you can't do that. If we implement #1793, this may be something that becomes possible.

> Also your recommendation doesn't seem to work? I don't see any tray icons that way. AFAIK "tray-position" is to place it on the right or left of the bar, not a monitor.

My recommendation was for how to have it always on the same monitor instead of it being random.
