### ISSUE TITLE
Github module displays label when offline

### ISSUE THREAD

**Issue by kopecs** [polybar/polybar#1815]
## Describe the issue
When offline the github module displays regardless of `empty-notifications = false`. 

**Expected behavior:**

The module either displays only when the last query resulted in a non-zero number of notifications or does not display even when offline (alternatively, allows for a custom offline label to be set).

**Actual behavior:**

Github module always displays when offline.

**Was it working before?**

Same behavior since I've first used github module (~3 weeks).

* Did you also experience this bug in an earlier version of polybar?

Yes.

* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[colors]
background = #222
background-alt = #444
foreground = #dfdfdf
foreground-alt = #888
primary = #ffb52a
secondary = #e60053
alert = #bd2c40

[bar/main]
monitor = ${env:MONITOR:eDP-1}
width = 100%
height = 2.5%
radius = 6.0
fixed-center = false
bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0
line-size = 2
padding = 1
module-margin = 1

font-0 = "Noto Sans Mono:size=10;1"
font-1 = "Noto Sans Mono:size=10;1"
font-2 = "Noto Sans Symbols:size=10;1"
font-3 = "Noto Sans Symbols2:size=10;1"

modules-left = 
modules-center =
modules-right = github

tray-position = right
tray-padding = 2
tray-maxsize = 24

[global/wm]
margin-top = 0

[module/github]
type = internal/github
token = ${file:~/.config/github/notifications.token}
empty-notifications = false
;label = %{u#ff9900 +u} %notifications% %{u-}
label = %{u#0099ff +u} 📫 %{u-}
interval = 10

[settings]
screenchange-reload = true

; vim:ft=dosini

```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*

Disconnect any internet connection.

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: module/github: cannot complete the request to github: Couldn't connect to server
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*
With full config:
* Online (No notifications):
![2019-06-17-165021_1919x23_scrot](https://user-images.githubusercontent.com/18350374/59635926-5276a900-9120-11e9-8c0a-3bc1a1af137a.png)
* Offline:
![2019-06-17-165110_1919x22_scrot](https://user-images.githubusercontent.com/18350374/59635945-5c001100-9120-11e9-9378-d2072e9ce17b.png)
## Environment:
* WM: xmonad 0.15-12
* Distro: Arch Linux
* Output of `polybar -vvv`:

polybar 3.3.1

Features: +alsa +curl -i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now

## Additional context
*Add any other context that you think is necessary about the problem here.*
Appears to occur as a result of drawing whenever the condition in line 81 of github.cpp is met (`0 != notifications || m_empty_notifications`), in conjunction with the choice to return `-1` from `get_number_of_notifications` when a non 200 http response is received and passing that directly to `update_label`.

**Comment by kopecs** [comment]
Seems related to #910.

**Comment by patrick96** [comment]
Yeah, some edge cases were not considered in the github module. If you add `%notifications%` to the label it would display `-1`, correct?
#910 should indeed fix all of this. If you want to, feel free to fix the segfault in the PR and resubmit it :)

**Comment by kopecs** [comment]
It does show `-1` as expected if I add `%notifications%`. The segfault from the PR should occur immediately when launching polybar, correct? I don't have much c++ experience, but it appears to occur for some reason when clearing `m_label_offline`. I'll look into it further and submit a PR if I can figure it out.

**Comment by patrick96** [comment]
>  The segfault from the PR should occur immediately when launching polybar, correct?

Correct.

It's likely a null pointer dereference. Don't worry if you can't find the cause, we can also fix this later. But right now this has a very low priority for us.

**Comment by Lomadriel** [comment]
> I'll look into it further and submit a PR if I can figure it out.

From what I see, i think it crashes because `m_label_offline` is `nullptr`.
https://github.com/polybar/polybar/blob/4b38fdba20605e27f5070618fade25af6b1e2f29/src/modules/github.cpp#L103

If you look into the constructor it seems that the label is never loaded.
We have two options here:
1. We want to keep the old behavior by **default** and we should display the online label with `-1`
2. We change the behavior and display something like `Offline`

------
To fix the issue:

It seems that the `format-offline` is defaulted to `""` rather than `TAG_LABEL_OFFLINE`.
https://github.com/polybar/polybar/blob/4b38fdba20605e27f5070618fade25af6b1e2f29/src/modules/github.cpp#L29

Once this modification done, depending of the selected option, we should modify this line:
https://github.com/polybar/polybar/blob/4b38fdba20605e27f5070618fade25af6b1e2f29/src/modules/github.cpp#L32
1. If we choose the first option, then the label should copy the online label and set `%notifications%` to `-1`. (Just after loading this label)
2. If we choose the second option, you should load `m_label_offline` optionally, like here: 
https://github.com/polybar/polybar/blob/4b38fdba20605e27f5070618fade25af6b1e2f29/src/modules/github.cpp#L26 I think the default value should be "Offline" or something like that.

Do you have a preference on that @patrick96?
In my opinion we should choose the second option.

Once, we agree on something, you could try to implement that @kopecs, if you need more help don't hesitate to ask.

------

Maybe we should also deprecate the key `label` and replace it by `label-online`?

**Comment by kopecs** [comment]
I've created a PR with the aforementioned second option, which seemed fairly robust from the perspective of not immediately crashing (or at all during testing for that matter) with several different configs, both with and without values for each option, although I didn't test every possible combo.

**Comment by Lomadriel** [comment]
Thanks! I'll review that ASAP.
