### ISSUE TITLE
Global menu (port vala-panel-appmenu as Polybar module)

### ISSUE THREAD

**Issue by aposuit** [polybar/polybar#1840]
I have moved from KDE (includes plugin for global menu) to BSPWM with Polybar and, to maintain that functionality, I had to install [vala-panel](https://github.com/rilian-la-te/vala-panel) as a second panel to put [vala-panel-appmenu](https://github.com/rilian-la-te/vala-panel-appmenu) in it.

[Vala-panel-appmenu](https://github.com/rilian-la-te/vala-panel-appmenu) is available for Vala Panel (fork of LXPanel), XFCE4-panel, Mate-panel and Budgie-panel.

Is it possible implement the vala-panel-appmenu code as a Polybar module?

**Comment by Lomadriel** [comment]
I don't think this will be implemented someday. It's really a big feature and it would take a lot of time and since the Polybar team isn't so big, I think the Polybar team can't afford to add and maintain this in Polybar. Moreover Polybar is more a status bar than a taskbar.

If you really want to have a menu in Polybar, I advise you to find a menu that can be launched in shell and bind it in Polybar using the `script` or `menu` module.

P.S.: This is my personal opinion, not the opinion of the whole team.

**Comment by patrick96** [comment]
Please don't ask the same question here and on [reddit](https://www.reddit.com/r/Polybar/comments/cgtfc9/global_menu_module/).

This cannot be done in polybar. That's also not the direction we want polybar to go in. Polybar should be about displaying information in a simple bar, no extra popups and so on. You could write a script module that does something similar but without the popups, so whenever you click on a menu item, the submenu gets displayed on the bar, this is far from trivial though.

Also, I have never seen someone use a WM without a desktop environment and also use such an app menu. Most functionality is reachable with key bindings and applications also display those menu items in their own window

**Comment by lepidopteralady1781** [comment]
> Please don't ask the same question here and on [reddit](https://www.reddit.com/r/Polybar/comments/cgtfc9/global_menu_module/).
> 
> This cannot be done in polybar. That's also not the direction we want polybar to go in. Polybar should be about displaying information in a simple bar, no extra popups and so on. You could write a script module that does something similar but without the popups, so whenever you click on a menu item, the submenu gets displayed on the bar, this is far from trivial though.
> 
> Also, I have never seen someone use a WM without a desktop environment and also use such an app menu. Most functionality is reachable with key bindings and applications also display those menu items in their own window

different person

**Comment by patrick96** [comment]
Oh...

Sorry :man_facepalming: 

The posts were made around the same time, so I assumed they were made by the same person :smile:

**Comment by tobyscott25** [comment]
I must admit this would be an amazing addition to tiling WMs. Since the windows are all opened, closed, resized, and moved around with key-bindings, imagine if we could do away with the ugly app menu at the top of each window and have a single global menu at the top of the screen.

Would it even be possible to build a polybar module that could do this?

**Comment by Ali-Aref** [comment]
any updates on this?

**Comment by tobyscott25** [comment]
@Ali-Aref I don't think it'll ever happen in Polybar 😞 But this guy did it by using the XFCE Panel with i3 in place of Polybar
