### ISSUE TITLE
Network module abbreviations

### ISSUE THREAD

**Issue by SicariusNoctis** [polybar/polybar#1848]
The network module uses more space than it needs to. Compare:

![](https://i.imgur.com/ejaR1uI.png)

Using the abbreviations `K, M, G` and dropping the extra space can improve things significantly.

```
123 KB/s 456 KB/s
versus
123K 456K
```

**Comment by patrick96** [comment]
I think it is highly subjective which of the two is "better". I don't think we need to change how the network module looks just because it is shorter.

In #1063 we are considering greatly improving the expressiveness of tokens. There the `#` modifier could be used to display the shorter version, though I also thought about it switching between bits and bytes. In any case we will track this over there.

**Comment by SicariusNoctis** [comment]
This is more problematic with low-res displays or if your polybar is already filled up with other content.

Saving characters is good: it allows room for more content in the polybar, or at the very least provides more whitespace to work with (aesthetics).
