### ISSUE TITLE
Real Transparency for Tray

### ISSUE THREAD

**Issue by cwrau** [polybar/polybar#1850]
## Is your feature request related to a problem? Please describe.
I have an audio visualizer beneath polybar and set polybar to be transparent.
This works perfectly (and looks awesome!).
But the tray is only pseudo-transparent, as I've read in the docs.
Having the bar real-transparent would be awesome!

## Why does polybar need this feature?
So people can put dynamic windows beneath polybar for aesthetics.

## Describe the solution you'd like
'Just' a real-transparent tray

## Describe alternatives you've considered
I couldn't find any

## Additional context
![image](https://user-images.githubusercontent.com/14326070/62528066-8b87eb80-b83c-11e9-846a-ba9eeedd8018.png)

**Comment by Lomadriel** [comment]
Real transparency for the systray was removed from polybar in favor of pseudo-transparency so I don't think, we'll reintroduce real transparency for the systray. I can't give you the reason since I wasn't in the team when this decision was made.

Anyway, the current systray implementation is buggy and we are reworking this implementation to transform it in a module but I can't give you a release date for this new tray.

**Comment by cwrau** [comment]
Oh, ok.
Is there an issue for that rework, or something else I can subscribe to?

**Comment by Lomadriel** [comment]
I think you can subscribe to these issues: #913 and #314.

**Comment by cwrau** [comment]
Thanks, I'll do that!

**Comment by patrick96** [comment]
When @bennofs implemented pseudo-transparency we decided to not support real transparency in the tray anymore because it would add too much complexity to the tray which is already quite buggy. We also thought the impact would be minimal since not many people actively display stuff behind the bar, you're a rare exception :wink:

**Comment by cwrau** [comment]
People keep telling me....
😄
But I can understand, thanks for the info!

**Comment by bennofs** [comment]
The problem with real transparency for the tray is that many applications also do not handle it correctly so you end up with artifacts. I think there's some apps that do "pseudo-transparency" for their tray icons themselves, so if the tray then has RGBA background transparent and the application doesn't expect a transparent background, you end up with ugly black icons. This is very hard to fix (I think some of the tray implementations that support this do manual post-processing of the icon to detect the background and replace that with transparent color).

**Comment by Lomadriel** [comment]
@bennofs Thanks for the explanation. I don't know how we'll implement this as a module since the bar supports transparency (for now), but maybe we'll need to do this manual post-processing :/
