### ISSUE TITLE
Feature request: make it possible to show or hide a numeric module based on its value

### ISSUE THREAD

**Issue by sagotsky** [polybar/polybar#1856]
I have the cpu, memory, and battery modules.  I only care about the first 2 when usage is high.  It would be nice to be able to ignore them and get back some screen space when they're not high.

One solution is to simply define a threshold.  `hide-if-below: 70` or something.  I don't think that works for the battery where I only want to see it below a threshold, so you'd need an inverse `hide-if-above: 50`.  

Another option that feels a little hacky but a little more inline with the rest of polybar's config would be numbered format or label options.

My cpu module is a series of `ramp-load-n` lines, each with a different icon.  Maybe I could set `format-{0-7}` to `""` and only define a format in the remaining tier?  I think this approach would feel pretty natural to polybar users.

**Comment by patrick96** [comment]
Something like `format-warn` has been suggested multiple times before (#570, #956). With that you could set the other formats to `""` to only show the module in the warn state.

It's on our TODO list, it will probably be implemented once we refactor our modules to use a proper state machine, can't give you an ETA though.

Being able to specify formats similar to ramps may be something to consider but it doesn't feel intuitive to me. I think `format-warn` will be enough for most people.

I am going to close this since #570 and #956 request about the same thing.

**Comment by x001F** [comment]
Are you done yet @patrick96?
