### ISSUE TITLE
bspwm: monocle label is displayed when it's just single_monocle

### ISSUE THREAD

**Issue by mdutra** [polybar/polybar#1880]
## Describe the issue

When bspwm's single_monocle is enabled, the layout will automatically change to monocle when there's only one window in a particular desktop. When this happens, polybar displays the monocle label as if the actual monocle layout was set by the user.

This shouldn't happen because, when I'm in single_monocle, I can still toggle the monocle layout:

- single_monocle with monocle layout enabled: next window will open in monocle.
- single_monocle with monocle layout disabled: next window will open in tiled

In these two cases polybar shows the monocle label so I can't know the status of the desktop layout.

**Expected behavior:**

The monocle label is not displayed when it's just single_monocle.

**Actual behavior:**

The monocle label is displayed when it's single_monocle, but the actual monocle layout is off.

**Was it working before?**

I don't know.

## To Reproduce
```dosini
[module/bspwm]
inline-mode = false
format = <label-state> <label-mode>
label-monocle = M
```

Enable single_monocle: `$ bspc config single_monocle true`

Disable monocle for the current desktop: `$ bspc desktop -l tiled`

Leave only one window open in the current desktop and polybar will show the "M".

## Polybar Log
After `$ bspc config single_monocle false`:
```
* module/bspwm: Parsing socket data: MLVDS-1:oDesktop:oDesktop:ODesktop:LT:TT:G
* module/bspwm: Rebuilding cache
* Redrawing bar window
```

After `$ bspc config single_monocle true`:
```
* module/bspwm: Parsing socket data: MLVDS-1:oDesktop:oDesktop:ODesktop:LM:TT:G
* module/bspwm: Rebuilding cache
* Redrawing bar window
```

## Environment:
* WM: bspwm
* Distro: ArchLinux
* Output of `polybar -vvv`:
```
polybar 3.3.1

Features: +alsa +curl -i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) -render -damage -sync +composite +xkb +xrm +xcursor

Build type: RelWithDebInfo
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Werror -Wno-noexcept-type -pedantic -pedantic-errors
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

You can use the userLayout from `bspc query -T -d` to find out if monocle was set by the user, as mentioned here baskerville/bspwm#1013.

**Comment by jtdubs** [comment]
@mdutra, unfortunately I believe this is working-as-designed.  The documentation for BSPWM's single_monocle settings indicates:

`single_monocle - Set the desktop layout to monocle if there’s only one tiled window in the tree.`

So, despite the reason for being in monocle mode being different (automatic vs. manual), BSPWM views this as genuinely changing the layout to monocle mode.

This aligns with the output of `bspc subscribe report` which includes `:LM:` in the reports for single_monocle mode, which indicates the layout of the focused desktop is monocle.

In fact, at this point `bspc subscribe report` doesn't even issue a new report if you toggle monocle mode with `bspc desktop -l next` while in single_monocle mode, so it's not clear what event Polybar could key off of to accomplish this.

I do agree with you that it would nice to differentiate between these states.  To me this feels like a feature request against BSPWM rather than a bug report against Polybar.  They could easily make this information available in their report format by adding a new `l(T|M)` entry that contains the user's selected layout just like their `L(T|M)` entry shows the current layout.  Accomodating that new report field in Polybar looks easy and clean.

**Comment by mdutra** [comment]
@jtdubs, sorry if I wasn't clear, but I reported the issue before on bspwm: baskerville/bspwm#1013.

It was suggested to use the command `bspc query -T -d` which returns the `userLayout` and `layout`.
`userLayout` will be monocle but ignoring single_monocle.

But you're right about this:

> In fact, at this point `bspc subscribe report` doesn't even issue a new report if you toggle monocle mode with bspc desktop -l next while in single_monocle mode

And I agree it's better to make the changes in `bspc subscribe report`.

I also think there's a problem with the definition of single_monocle, but I'll reopen baskerville/bspwm#1013 and ask to make the changes there.

Thanks a lot @jtdubs!

**Comment by MahouShoujoMivutilde** [comment]
@mdutra if you still interested in this - i made a workaround script to show userLayout in polybar.

```sh
#!/usr/bin/env sh
# let's name it bsplayout

userLayout() {
    case $(bspc query -T -d | jq -r .userLayout) in
        monocle)
            echo " M "
            ;;
        *)
            echo " "
            ;;
    esac
}

bspc subscribe report | while read -r line; do
    userLayout
done
```

(depends on [jq](https://github.com/stedolan/jq))

And for polybar config:

```ini
[module/bsplayout]
type = custom/script
exec = bsplayout
tail = true
```

Note that it has one downside - bspc subscribe seems to be silent until you actually interact with nodes (just changing layout with a hotkey is not enough).



If you not ok with this - you'll be better off calling bspc query every e.g. 0.1s:

```ini
[module/bsplayout2]
type = custom/script
exec = bspc query -T -d | gron | grep -Po 'userLayout = .\K(tiled|monocle)'
interval = 0.1
```

(Note that jq is slow af compared to bspc query alone, so i used [gron](https://github.com/tomnomnom/gron) instead).

**Comment by ask1234560** [comment]
```
[module/bspwmlayout]
type = custom/script
interval = 0.1
exec = bspc query -T -d | grep -oP 'userLayout.*?,' | grep -q 'monocle' && echo M
```
Just to add to @MahouShoujoMivutilde answer, this one is faster.
