### ISSUE TITLE
Failed to build:   Missing required python module: xcbgen

### ISSUE THREAD

**Issue by mvrozanti** [polybar/polybar#1882]
## Build Process
`git clone https://github.com/polybar/polybar/; cd polybar; ./build.sh`

* Output of `git describe --tags`:
3.4.0-14-g5a309f0

## Build Log
http://ix.io/1WCE

## Environment:
`Linux 5.3.1-arch1-1-ARCH x86_64`

## Additional context
I think this is related to the discontinuation of python2 and it's interference with xcb-proto package. I tried manually editing `lib/xpp/CMakeLists.txt` from python 2.7 to python 3.7 with no luck. I also have `pyenv` installed which could be messing everything up further.

**Comment by patrick96** [comment]
It's likely more to do with pyenv than python2 since your system still has python2 installed. What distro are you using?

Could you give me the list of files provided by the package that provides xcbgen? That's generally either `python-xcbgen` or `xcb-proto`.

**Comment by mvrozanti** [comment]
I'm using Arch Linux. `xcb-proto 1.13-2` is installed with `pacman`.

**Comment by patrick96** [comment]
Yeah, then it's definitely pyenv. Try running `pyenv global system` in the terminal before you run cmake.

**Comment by mvrozanti** [comment]
I tried that from reading the other issue, but I get the following message:
`pyenv: version `system' not installed`

**Comment by patrick96** [comment]
Hmm. Could you post the output of `python3 -c "import re,xcbgen;print(re.compile('/xcbgen/__init__.py.*').sub('',xcbgen.__file__))"` on your system.

**Comment by mvrozanti** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'xcbgen'
```

**Comment by patrick96** [comment]
I'm not really that familiar with pyenv so this may not work. From googling I found a few other ways to temporarily disable pyenv: `pyenv local system` and `pyenv shell system`. If those doesn't work try manually editing the `PATH` and `PKG_CONFIG_PATH` variables to remove all mentions of `pyenv`. If that doesn't work either, remove the pyenv initialization code from your shell init script before building polybar.

**Comment by mvrozanti** [comment]
I tried running `build.sh` with the following:
`PATH=$(echo $PATH | sed -e 's/:\/home\/nexor\/.pyenv\/plugins\/pyenv-virtualenv\/shims//' | sed -e 's/:\/home\/nexor\/.pyenv\/shims//' | sed -e 's/:\/home\/nexor\/.pyenv\/bin//') ./build.sh -f`

But it still [fails to build the project](http://ix.io/1WDA)

**Comment by patrick96** [comment]
Did you clean the build directory before you did this? Seems like it is still invoking a pyenv version of `shphinx-build`. I recommend completely deleting the `build` directory before every try.

Since you are using arch, you can also use the [aur package](https://aur.archlinux.org/packages/polybar/). Of course this would run into the same installation issues but arch provides an easy way to compile packages in a [clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot). Install the `devtools` package and try this:

```bash
git clone https://aur.archlinux.org/polybar.git/
cd polybar
extra-x86_64-build
```

**Comment by mvrozanti** [comment]
This is insanely complicated, I give up

**Comment by patrick96** [comment]
> But there has to be another way to install this.

This is the way you install arch packages if your system interferes with the compilation. You could also use an aur-helper that can natively build inside a chroot (like [aurutils](https://github.com/AladW/aurutils)).

polybar requires a working python environment with xcbgen and sphinx to compile properly. On arch this can be achieved with native arch packages as long as pyenv (or something similar) doesn't interfere. If they do, you will need to provide those python dependencies from pyenv. So in your case installing the two dependencies via pip in the pyenv version you are using should work.

I'm kind of confused why there isn't an easy way to use system python in the current terminal, because this would solve all those problems.

**Comment by mvrozanti** [comment]
I understand that installing `xcb-proto` module for python would have polybar build out of the box. But all I see when I do `pip search xcb`, is this:

```
xcffib (0.8.1)               - A drop in replacement for xpyb, an XCB python binding
xpybutil (0.0.6)             - An incomplete xcb-util port plus some extras
uncrumpled_xpybutil (0.0.1)  - An incomplete xcb-util port plus some extras
```

**Comment by patrick96** [comment]
I have also not found any mention of it in pip. So there is literally nothing we can do. You need system python while building polybar or at the very least your pyenv version needs to be able to use modules installed via pacman packages.

**Comment by patrickcurl** [comment]
Hit this problem today for anyone else...my simple work around was use pamac-manager (gui) .. it doesn't pyenv/path vars aren't loaded so it sometimes installs things I can't when using shell.

**Comment by mrdotb** [comment]
I got similar problem removing pyenv temporary from $PATH and removing the build folder solved it for me. 
`$> export PATH=$( echo $PATH | awk '
{ split($0, res, ":", seps)
    for (i in res) {
      if (!match(res[i], /pyenv/)) {
        printf res[i]
        if (i < length(res)) {
          printf ":"
        }
      }
    }
    printf "\n"
}') `
`$ rm -rf  /build`

**Comment by tsujp** [comment]
`pyenv global system` before build fixed it for me.

**Comment by BlueLovin** [comment]
`sudo apt install python3-xcbgen` fixed it for me!

**Comment by Nova-Striker** [comment]
@BlueLovin  , Wow . This comment should be on the top. It fixed for mine too

**Comment by Swivelgames** [comment]
fwiw, `pyenv local system` fixed it for me! :tada:
