### ISSUE TITLE
Clicking on the date module on the right of a time module will make it disappear

### ISSUE THREAD

**Issue by catzybluphish** [polybar/polybar#1905]
## Describe the issue
I have two separate modules:
```
[module/date]
type = internal/date
date = %d/%m/%Y
date-alt = %A, %B %Y
label = %date%

[module/time]
type = internal/date
time = %I:%M %p
label = %time%
```
As you can see, they're both using the same type because time didn't have it's own and I wanted the modules to be kept separate (time at center, date at right).

**Expected behavior:**

Clicking on the date module toggles the date/date-alt.

**Actual behavior:**

Clicking on the date module hides the time, and clicking again shows it. The text simply just vanishes.

## To Reproduce

Here's my [config](http://ix.io/1Zmz). Note that the time module disappears only when it's on the left of the date module. Even if it is on `modules-right` where the date module is located, it must be e.g. `modules-right = pulseaudio date time`, not `modules-right = pulseaudio time date` for it to not disappear.

## Polybar Log

There are no messages when running polybar through the terminal and clicking on the broken date module.

## Environment:
* WM: bspwm
* Distro: Arch
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

I believe it has something to do with the time and date module using the same type.

**Comment by patrick96** [comment]
Thanks for reporting. This is unfortunately a known bug tracked in #1172. See also our [Known Issues](https://github.com/polybar/polybar/wiki/Known-Issues#with-multiple-modules-of-the-same-type-actions-on-those-modules-control-the-leftmost-module).

You are right it is because they are using the same type. When you click on the module it produces an internal `datetoggle` event. The problem is that both date modules support that event so it is handled by the leftmost module. There is unfortunately nothing you can do right now (other than merging the two modules).
