### ISSUE TITLE
part of formatting options doesn't work with bspwm's module labels

### ISSUE THREAD

**Issue by mighty9245** [polybar/polybar#1911]
so... i'm trying to highlight a focused desktop somehow but with no luck... i don't think that it's a bug in the polybar, i'm rather doing something wrong but i don't know what exactly... here is my polybar config: https://hastebin.com/raw/awowosoyas

initially i read article on formatting and decided to format a focused desktop label in bold. i added second font (`font-1 = NotoSansMono-Bold:size=12;3`) and set it for focused label (`label-focused-font = 1`) but nothing happened. i decided to gave up on this because it is only shown in article on formatting and decided to try something other. then i tried to underline it with `label-focused-underline = #fff0f0f0` but nothing happened again and i'm totally gave up. i also tried overline, but result is the same.

but foreground and padding are working, that's why i said part.

help me

**Comment by patrick96** [comment]
In general please don't use the issue tracker for help with troubleshooting. See our [support page](https://github.com/polybar/polybar/blob/master/SUPPORT.md) for places where you can ask questions.

the `-font` property is 1-indexed, this means that `label-focused-font = 1` actually refers to `font-0` use, `label-focused-font = 2`.

As for the underline, you need to set `line-size` in your bar section otherwise the size of the underline is 0 (there was an error on the wiki saying the default value was 1).

**Comment by mighty9245** [comment]
@patrick96, oh, ok, i'm sorry.

is there a reason to keep `-font` property 1-indexed instead of making it 0-indexed?

about underline... i've been configuring polybar property-by-property looking at the wiki but somehow i've missed the `line-size` property, that's my bad. but i still found an actual mistake in the wiki so this issue is not that useless! :)

thank you for your help!

**Comment by patrick96** [comment]
It's mostly because we don't want to break existing configs and because fonts are also 1-indexed in lemonbar (with which we want to stay compatible).
