### ISSUE TITLE
Wrong ESSID for WiFi

### ISSUE THREAD

**Issue by jonatanolofsson** [polybar/polybar#1927]
## Describe the issue
Polybar displays the ESSID of a network I have previously been connected to, not the current one.
E.g, the name of my home network is shown even when I'm at work.

`iwgetid -r` shows the correct network

**Expected behavior:**
The currently connected network is displayed in the bar

**Actual behavior:**
Another (previous?) network name is displayed as ESSID.

**Was it working before?**
This has not worked for me for a long time.

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```
[module/wlan]
type = internal/network
interface = wlp3s0
interval = 3.0

format-connected = <ramp-signal> <label-connected>
format-connected-underline = #9f78e1
label-connected = %essid%
```

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e237)
warn: Dropping unmatched character  (U+e016)
warn: Dropping unmatched character  (U+e26f)
warn: Dropping unmatched character  (U+e238)
warn: Dropping unmatched character  (U+e016)
```

## Environment:
* WM: i3wm
* Distro: arch
* Output of `polybar -vvv`:
```
polybar 3.4.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
I have been trying to follow the code to where the ESSID is updated, but I'm not sure I follow, as the only reference i find is `query_essid`, but this is not called anywhere and m_essid obviously gets filled with something...

**Comment by patrick96** [comment]
This looks like the same issue as #1822.

The SSID is supposed to be queried on every update of the module and it goes like this:

`query` is called on the network adapter every `update` (every `interval` seconds):

https://github.com/polybar/polybar/blob/6849b8a56b42b767b48bbba9c4e77847139f1b0b/src/modules/network.cpp#L83-L90

This then goes to `net_nl.cpp` adapter (it seems you looked at `net_iw.cpp`, which is the legacy adapter):

https://github.com/polybar/polybar/blob/6849b8a56b42b767b48bbba9c4e77847139f1b0b/src/adapters/net_nl.cpp#L18

In there we register the `scan_cb` function as a callback:

https://github.com/polybar/polybar/blob/6849b8a56b42b767b48bbba9c4e77847139f1b0b/src/adapters/net_nl.cpp#L38

Presumably that callback is triggered somewhere later on. `scan_cb` then calls `parse_essid`:
https://github.com/polybar/polybar/blob/6849b8a56b42b767b48bbba9c4e77847139f1b0b/src/adapters/net_nl.cpp#L134

`parse_essid` then parses the ssid and sets `m_essid`, which is used for the `%essid%` token.

We would be extremely grateful if you could help debug this. If this is easily reproducible by you, I think it would be easiest to compile polybar with debug symbols (add `-DCMAKE_BUILD_TYPE=Debug` to `cmake` command), track the `query` call and see why `m_essid` is never set.

I think `parse_essid` is never called since calling that function resets the ssid and an empty ssid means that the module thinks it's not connected (which is not the case here). So either `scan_cb` is never called or `scan_cb` returns prematurely.

**Comment by jonatanolofsson** [comment]
Thank you, that does in fact seem to be the same issue (Searched for "wifi" problems before posting, so that one didn't show..)

It is in fact 100 % reproducible on my computer, so I'll see what I can do to debug.

Closing in favor of #1822

**Comment by patrick96** [comment]
> It is in fact 100 % reproducible on my computer, so I'll see what I can do to debug.

Great, thank you very much!
