### ISSUE TITLE
installation interrupted due to a syntax error

### ISSUE THREAD

**Issue by zazajin** [polybar/polybar#2005]
![DeepinBildschirmfoto_Bereich auswählen_20200206224341](https://user-images.githubusercontent.com/60759083/73981266-2cfa1200-4932-11ea-918c-dd4b784b90f5.png)

I am using Deepin OS , installed all dependencies and follow overall all the installation guide. I am new to Linux so  I am sorry in case I did not even do a " correct " issue submit.

**Comment by patrick96** [comment]
Thanks for informing us. The problem seems to be that for debian the `python-xcbgen` package still comes with the python2 bindings and we recently stopped supporting python2.

You need [`python3-xcbgen`](https://packages.debian.org/sid/python3-xcbgen) instead of `python-xcbgen`, I have updated the wiki. Please note that python3-xcbgen is only available in debian unstable (sid)

**Comment by zazajin** [comment]
Hello , thank you for your fast answer.
I already installed python3-xcbgen , sadly I still get the same issue.  Is there a way to "force" to use python3 in the building-process ?

By the way, when I install polybar via snapcraft , it at least doesnt give me any issues, but it is still not running ( obviously, since I dont have the polybar on my desktop ) . 

As I said, I am really new to Linux so I really would appreciate help. I like deepin and would like to use it now as my first distribution but it doesnt come with a good topbar , I really want the polybar. 

Thank you !

**Comment by patrick96** [comment]
Hmm, have you uninstalled `python-xcbgen`? It's possible that polybar still picks up the python2 version because the `python` executable is python2. Also make sure to delete the `build` folder before you start building again because the old paths may still be saved somewhere.

> By the way, when I install polybar via snapcraft , it at least doesnt give me any issues, but it is still not running ( obviously, since I dont have the polybar on my desktop ).

If you can install it via snapcraft, you should also be able to run it.

**Comment by zazajin** [comment]
It doesnt start sadly. I can run / execute it,  but the polybar doesnt show up.

I actually got a build-folder in my trash and I cant remove it. There might be the issue.

**Comment by patrick96** [comment]
> It doesnt start sadly. I can run / execute it, but the polybar doesnt show up.

That's unrelated to the installation issue. Polybar should give you some error messages to tell you what's wrong.

> I actually got a build-folder in my trash and I cant remove it.

If it's in the trash it shouldn't affect the compilation. I am talking about the `build` folder you run `cmake` and `make` in. How exactly are you building polybar? Did uninstalling `python-xcbgen` and only having `python3-xcbgen` installed work?

**Comment by zazajin** [comment]
![DeepinBildschirmfoto_Bereich auswählen_20200207144612](https://user-images.githubusercontent.com/60759083/74034483-a8060b80-49b8-11ea-8cdc-d0833ae4486a.png)


If I want to remove only " python-xcbgen " via  using command " sudo apt purge python-xcbgen " this happens.

I dont want to disturb you that much , thank you very much anyways and sorry !

**Comment by patrick96** [comment]
From what I am seeing the package was actually removed, it just couldn't delete all the folders associated with that package. If you are sure that no other package owns files inside the `/usr/lib/python2.7/dist-packages/xcbgen` folder, you can delete it and try to install polybar again.

**Comment by zazajin** [comment]
In the folder there is only a cache-folder left. I dont have the permission to delete it via desktop. Is there any command to do so ?

**Comment by zazajin** [comment]
Little update : 

I removed polybar ( the snap version ) and everything else related with polybar. When I rebooted my system the folder /usr/lib/python2.7/dist-packages/xcbgen  was gone, too. 

Then I git clone polybar , and used following command : 

cd polybar && ./build.sh   and it actually worked ! 
At least at the end it says : " Build complete !  " 

How I am supposed to start it now ? 
I went to the file polybar/build/bin/   and there is an executable file called " polybar " . When I try to run it, nothing happens. Same when I tried to run it via snap. Could it be that it just doesnt work with deepin OS ?

**Comment by patrick96** [comment]
The build.sh should have also asked you to install polybar, if you did polybar is also installed to `/usr/local/bin/polybar`, otherwise you can go into the `polybar/build` folder and run `sudo make install`.

> When I try to run it, nothing happens

Nothing? Polybar produces no output in the terminal where you ran it?

**Comment by zazajin** [comment]
Ok - I used  sudo make install   in polybar/build and it installed it succesfully. How am I supposed to start it now ?

**Comment by patrick96** [comment]
You need to first create a config file and put it in `~/.config/polybar/config`. See the [Wiki](https://github.com/polybar/polybar/wiki/Configuration) for a list of configuration options.

There should also be a sample configuration in `/usr/local/share/doc/polybar/config` that you can use as an inspiration.

Once you have a config file you can run `polybar BAR` where `BAR` is the name you gave the bar in the config. So when you have `[bar/xyz]` you run `polybar xyz`.

I'm closing this since the original build issue is resolved.
