### ISSUE TITLE
Check for configuration file at /etc/polybar/config as a fallback

### ISSUE THREAD

**Issue by samueloph** [polybar/polybar#2016]
Coming from the Debian packaging of polybar.

This feature request is for a little bit more than what the tittle says...

Polybar currently has the [following precedence](https://github.com/polybar/polybar/blob/fab8437ff133a0f154bf181ff173ed979fc8666f/src/main.cpp#L107-L115) for loading the `config` file:
https://github.com/polybar/polybar/blob/fab8437ff133a0f154bf181ff173ed979fc8666f/src/main.cpp#L107-L115

1) `-c/--config` parameter
2) `$XDG_CONFIG_HOME/polybar/config`, if the variable is set
3) `$HOME/polybar/config`, if the variable is set
4) Throw error

I would like to propose the following behavior instead:
1) `-c/--config` parameter
2) `$XDG_CONFIG_HOME/polybar/config`, if the file exists (variable still needs to be checked)
3) `$HOME/polybar/config`, if the file exists (variable still needs to be checked)
4) `/etc/polybar/config`, if the file exists (and the file is installed there by default)
5) Throw error

So a logic change in the way the config file is handled: check if the file exists instead of if the variables to generate the location are set, and fallback to `/etc/polybar/config`, while also shipping the file there instead of `${CMAKE_INSTALL_DOCDIR}`:
https://github.com/polybar/polybar/blob/fab8437ff133a0f154bf181ff173ed979fc8666f/CMakeLists.txt#L163-L165

The reason is ask this is because that will make it easier to ship polybar working out of the box, so that `polybar example` will work without the user having to copy the file to their `$HOME`, and it will work for any user.

Please note that if you agree with this, a change in the README will be needed to reflect it.

**Comment by patrick96** [comment]
I completely agree with the way you are proposing to do fallback, the old way is kind of weird.

However, I don't want to ship our example config in `/etc/polybar/config`. Because it is not the *default* config, it is merely an *example*. It doesn't completely work for most people out-of-the-box because there are a lot of machine specific configurations. Polybar doesn't have a default config that is supposed to work for everyone out of the box.

We try to make the sample config work for most people and many things are configured during `cmake` (network cards, font names and battery name), but if polybar is prepackaged, those configurations will be for the machine that compiled polybar.

The plan is to at some point have a config that is either completely machine independent or have polybar auto-detect some things during runtime, but right now the sample config isn't in a state where people can use it without modifications.

**Comment by samueloph** [comment]
@patrick96 oh I totally missed this crucial detail :)

Just so the proposal is updated then:
1) `-c/--config` parameter
2) `$XDG_CONFIG_HOME/polybar/config`, if the file exists (variable still needs to be checked)
3) `$HOME/polybar/config`, if the file exists (variable still needs to be checked)
4) Generate config for the user, maybe asking for a confirmation first
5) Throw error

Of course it will be up for whoever is implementing this and you(upstream) to decide which way to go. Unfortunately I won't have time to submit a PR for now.

I would like to ask for another thing, since this file is to be considered as an example, to move it from `.../doc/polybar/config` to `.../doc/polybar/examples/config`, as a good practice.

**Comment by patrick96** [comment]
Hmm, so number 3 should probably be `$HOME/.config/polybar/config`.
And number 4 would definitely be nice to have, but we would need to develop an entirely new tool for that. And I think we wouldn't want to make it part of the config path resolve logic but rather a separate flag something like `--dump-config`. So I think this could be a separate goal.
So my proposal would be:


1. `-c/--config` parameter (if specified)
1. `$XDG_CONFIG_HOME/polybar/config`, if the file exists (variable still needs to be checked)
1. `$HOME/polybar/config`, if the file exists (variable still needs to be checked)
1. Throw error

> I would like to ask for another thing, since this file is to be considered as an example, to move it from .../doc/polybar/config to .../doc/polybar/examples/config, as a good practice.

Yeah, that's a good idea as well. This will require updating some paths in the wiki.

**Comment by samueloph** [comment]
@patrick96 agree 100%, I just think you forgot to edit the proposal as option 3 is still the same.

**Comment by patrick96** [comment]
You're right, I wrote the right one in the first sentence but just copy pasted the checklist. Fixed!

**Comment by nekiter** [comment]
It would be too much if polybar validate the config before assume that the specific config is the right one?
In this case it would be something like that:   

1.   `-c/--config `parameter (if specified) if the config has a problem then polybar throw the exception as it does today, since the user is passing a broken config actively.
2.  `$XDG_CONFIG_HOME/polybar/config`, if the file exists (variable still needs to be checked), then try to load the config, if that process fail then log a warning and continue the process trying the other options.
3. `$HOME/.config/polybar/config`, if the file exists (variable still needs to be checked), if that process fail then log a warning and continue the process trying the other options.
4. Throw error

When I say problems read, a config file that is broken for some reason and the polybar can parse it.
What do u guys think?

**Comment by patrick96** [comment]
@nekiter I don't see a use-case in falling back to another config if one of them has parsing errors. I can also imagine this being quite confusing. I also don't know of any program that behaves this way, so I'd rather not do that and only check if the file exists.
