### ISSUE TITLE
Missing required python3 module: xcbgen

### ISSUE THREAD

**Issue by dyc3** [polybar/polybar#2031]
## Build Process

I've made sure all the submodules are up to date.

```
mkdir build
cd build
cmake -DCMAKE_CXX_COMPILER="clang++" ..
make -j$(nproc)
```

* Output of `git describe --tags`: `3.4.0-78-g512c519`

## Build Log
Output of cmake
```
-- Trying to enable ccache
-- Couldn't locate ccache, disabling ccache...
-- No build type specified; using Release
-- Using supported compiler Clang-6.0.0
--  Build:
--    Version: 3.4.0-78-g512c519
--    Type: Release
--    CXX: /usr/bin/clang++  -Wall -Wextra -Wpedantic -Wno-error=parentheses-equality -Wno-zero-length-array -O3 -DNDEBUG
--    LD: /usr/bin/ld
--  Install Paths:
--    PREFIX:  /usr/local
--    BINDIR:  /usr/local/bin
--    DATADIR: /usr/local/share
--    DOCDIR:  /usr/local/share/doc/polybar
--    MANDIR:  /usr/local/share/man
--  Targets:
-- [X]   polybar-msg
-- [ ]   testsuite
-- [X]   documentation
--  Module support:
-- [X]   alsa (1.1.3)
-- [X]   curl (7.58.0)
-- [X]   i3
-- [X]   mpd (2.11)
-- [X]   network (libnl) (3.2.29)
-- [X]   pulseaudio (11.1)
-- [X]   xkeyboard (1.13)
--  X extensions:
-- [X]   xcb-randr (1.13)
-- [X]   xcb-randr (monitor support) (1.13)
-- [X]   xcb-composite (1.13)
-- [X]   xcb-xkb (1.13)
-- [X]   xcb-xrm (1.0)
-- [X]   xcb-cursor (0.1.1)
--  Log options:
-- [X]   Trace logging
-- XCB[XCB]: Found component XCB
-- XCB[ICCCM]: Found component ICCCM
-- XCB[EWMH]: Found component EWMH
-- XCB[UTIL]: Found component UTIL
-- XCB[IMAGE]: Found component IMAGE
-- Searching for xcbgen with python3
-- Searching for xcbgen with python
CMake Error at lib/xpp/CMakeLists.txt:70 (message):
  Missing required python3 module: xcbgen


-- Configuring incomplete, errors occurred!
See also "/home/carson/Documents/code/other/polybar/build/CMakeFiles/CMakeOutput.log".
See also "/home/carson/Documents/code/other/polybar/build/CMakeFiles/CMakeError.log".
```

## Environment:
* Distro (with Version): Ubuntu 18.04
* Output of `python --version`: `Python 3.6.9`

**Comment by patrick96** [comment]
We have recently dropped python2 support since python2 was sunset at the end of 2019. It looks like Ubuntu 18.04 doesn't provide a python 3 variant of xcbgen (but later versions provide `python3-xcbgen`).

I downloaded the python-xcbgen package provided with 18.04 and it might be possible that it can also run under python3. Could you try adding `-DPYTHON_XCBGEN=/usr/lib/python2.7/dist-packages` to your cmake command? This forces polybar to use the python2 xcbgen variant.

**Comment by dyc3** [comment]
Adding that flag lets cmake succeed. Should we automatically add this flag for builds on ubuntu 18.04?

**Comment by patrick96** [comment]
> make still fails:

Use a clean clone of the repo, we haven't used `version.hpp` since 3.3.0

> Should we automatically add this flag for builds on ubuntu 18.04?

I will update the xpp submodule to once again search for xcbgen with python2

**Comment by dyc3** [comment]
That's fixed it. Thanks

**Comment by T-Doc** [comment]
Just wanted to add that I needed the additional flag on a clean Arch install today (did not pull from AUR because of the config error). May I suggest hard coding that option as a fallback if CMake cannot find the package anywhere else, or at least as a suggestion to the user while running `build.sh`?

I've also seen chatter about these sorts of errors on the AUR page, so I might not be the only one having this issue now (and I'm not sure what exactly broke this, because just a week ago I build polybar from the AUR just fine, I was just trying to rebuild it on a new machine).
