### ISSUE TITLE
Shell command is parsed incorrectly

### ISSUE THREAD

**Issue by hmenke** [polybar/polybar#2040]
## Describe the issue

I have an IPC module to display my unread mail. To refresh manually I want to bind click-right to starting the corresponding systemd service. However, the command is not parsed correctly and I don't know why.

Originally reported on the Gitter chat, where I was advised to open an issue:
https://gitter.im/polybar/polybar?at=5e6eb26d9f25f2238b847970
https://gitter.im/polybar/polybar?at=5e6eb87cc8ddaf238c88f32b

**Expected behavior:**

Bar renders correctly.

**Actual behavior:**

Bar only renders up to the faulty module and shows an error in the terminal.

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar?

    I just wrote this module, so maybe, maybe not.

* If no, what was the last version where this worked correctly?

## To Reproduce
*A minimal but complete config with which the problem occurs:*
```dosini
[bar/default]
enable-ipc = true

font-0 = "DejaVu Sans Mono:pixelsize=10;1"
font-1 = "Noto Color Emoji:scale=10;0"

modules-center = mail

[module/mail]
type = custom/ipc
hook-0 = echo $(ls -1q ~/.cache/checkmail 2>/dev/null | wc -l)
initial = 1
format = "%{T2}📬%{T-} <output>"
click-right = "systemctl --user start $(systemctl --user list-timers --no-legend 'checkmail@*' | awk '{ print $NF }')"
```
*List any other steps needed to reproduce the issue besides starting polybar with the config you posted above.*
None

## Polybar Log
*Post everything polybar outputs to the terminal when you run it and the issue occurs below*
```console
$ polybar default
error: Failed to parse contents (reason: Unrecognized token 'y')
$ polybar -s default
%{c}%{A3:systemctl --user start $(systemctl --user list-timers --no-legend 'checkmail@*' | awk '{ print $NF }'): T2}📬%{T-} 0%{A}
```

## Screenshots
*If applicable, add screenshots to help explain your problem.*

## Environment:
* WM: `bspwm`
* Distro: Arch Linux
* Output of `polybar -vvv`:
```
polybar 3.4.2

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

## Additional context
*Add any other context that you think is necessary about the problem here.*

**Comment by hmenke** [comment]
You can work around the issue by putting the command in a hook and calling the hook in the `click-right` action.
```dosini
[bar/default]
enable-ipc = true

font-0 = "DejaVu Sans Mono:pixelsize=10;1"
font-1 = "Noto Color Emoji:scale=10;0"

modules-center = mail

[module/mail]
type = custom/ipc
hook-0 = echo $(ls -1q ~/.cache/checkmail 2>/dev/null | wc -l)
hook-1 = systemctl --user start $(systemctl --user list-timers --no-legend 'checkmail@*' | awk '{ print $NF }')
initial = 1
format = "%{T2}📬%{T-} <output>"
click-right = polybar-msg hook mail 2
```

**Comment by patrick96** [comment]
This is definitely a polybar bug. The formatting parser is tripping up when reading `awk '{ print $NF }'` because the formatting string generated for a click action is `%{A:<cmd>:}` and the parser is just searching for a `}` character when it looks for the end of the formatting block. But when `<cmd>` contains a `}` character, it will stop searching too early.

The only workaround is to not use `}` in your commands, put them into an external script and call that if possible. Your hook solution works too, but this issue appears in all modules, so this is not always possible.

---

Here is a minimal example that demonstrates this issue as well:

```dosini
[bar/example]
modules-left = text

[module/text]
type = custom/text
content = Text
click-left = echo "${HOME}"
```

This might be a tricky issue to fix. Currently when a formatting block is encountered, we look for the end of the formatting block and pass the text inside to the function that parses the actual formatting tags. Instead of searching for the end of the block beforehand, the function parsing the formatting tags should figure out when the block actually ends because only it knows that a `}` character inside an action command doesn't terminate the formatting block.

**Comment by Lomadriel** [comment]
Related: https://github.com/polybar/polybar/issues/1701

**Comment by patrick96** [comment]
@Lomadriel I don't think that this is related to #1701. There the problem is that formatting tags inside tokens are not sanitized when they should be, here there are no tokens involved and sanitizing formatting tags is also not the issue.

**Comment by FrenzyExists** [comment]
I think I found something, here's an example" `label-connected-maxlen`. I had a similar issue, but on the wifi. Could the `maxlen` thingy be the culprit as it seems to also affect the parsing? I say this cuz after commenting out the `maxlen` of my wifi polybar (it executed a script btw) the parser went bonkers, but its cuz it wasn't reading the entire thing.

**Comment by patrick96** [comment]
@FrenzyExists This is a different issue and largely unrelated to the one in this thread: #531

**Comment by FrenzyExists** [comment]
Oh I see, got it! Thanks :+1:
