### ISSUE TITLE
i3 icons wont change from qt5c and wont change manually

### ISSUE THREAD

**Issue by themythtoon** [polybar/polybar#2047]
## Describe the issue
hello i am new here, so sorry for the posible mistakes.

i do change my i3 bar with qt5c usually, but one day randomly the battery icon get bugged and now is a cloud. (the charge% is working properly)
after that all the icons did bug and now when i try to change the i3bar to the default icons i just cant.

what should i do ? btw what is the manjaro original icon pack in the i3bar ?

**Was it working before?**
yes, all was working normaly with diferent icons packs, i did change the bar icons a lot with qt5c

## Screenshots
if you can see up, the battery icon now is a cloud and the icons are from adwaita and i am using other icon pack,  i did try to change the icons from diferent ways and nothing happens

https://imgur.com/gallery/qAdof0I

## Environment:
* WM: i3
* Distro: manjaro
* Output of `polybar -vvv`: i dont know

**Comment by patrick96** [comment]
i3bar and polybar are not the same. It's not totally clear from the screenshot whether you are using i3bar or polybar but since polybar does not support these qt5c icon packs and you don't seem to have the `polybar` command on your machine, I'm assuming you are actually using i3bar.

The i3 repository that contains i3bar is [here](https://github.com/i3/i3/), but I think such a question is better asked on their [subreddit](https://www.reddit.com/r/i3wm/).

If I made a mistake and you are actually using polybar, please post your polybar config as well as the polybar output when you start your bar in the terminal and the output of the `polybar -vvv` command.
