### ISSUE TITLE
[polybar+i3] No workspaces if monitor is mirrored

### ISSUE THREAD

**Issue by HughJass** [polybar/polybar#2066]
I've got a laptop with built in screen called eDP1 and an external monitor named HDMI1. By default the monitors are mirrored, both screens show the same thing. However, i3 recognizes the monitor as eDP1 while polybar only sees HDMI1. This causes polybar to not display any workspaces if the pin-workspaces = true is used in the config. This is because polybar is asking i3 for all workspaces on monitor "HDMI1" and i3 doesn't return anything, as it only sees the monitor "eDP1". If i replace 
`workspaces = i3_util::workspaces(ipc, m_bar.monitor->name);` `with workspaces = i3_util::workspaces(ipc, "eDP1");` it works.

This is not a problem for me, I disable the integrated display anyway, but I thought it's interesting. Not sure if it's a bug in the i3, polybar or x itself. Maybe polybar could ask i3 for a list of monitors ? I know this is not a generic solution, but at least when i3 module is used it could solve this problem

**Comment by patrick96** [comment]
This is a polybar bug. The i3 module behaves correctly, the bug is that polybar doesn't recognize the laptop monitor (see #1191).

https://github.com/polybar/polybar/pull/1823 should fix this. Could you try that PR and see if it works?

---

We should maybe also consider allowing the user to specify a monitor for the i3 module.

**Comment by patrick96** [comment]
I have just merged #1823 which should fix this. Please reopen if this still occurs with the latest commit.
