### ISSUE TITLE
libjsoncpp error 

### ISSUE THREAD

**Issue by 1m-N00b** [polybar/polybar#2073]
##Error 
i update with `yay -Syu`
then output error when i started polybar with `polybar -r bar1`
`polybar: error while loading shared libraries: libjsoncpp.so.20: cannot open shared object file: No such file or directory`

##What i did
I know this **[problem](https://github.com/polybar/polybar/wiki/Known-Issues#error-while-loading-shared-libraries-libjsoncpp)** so i tried recompile.
But it's the same error again, and I couldn't resolve the error.

Then I checked in /lib to see if **libjsoncpp.so.20** existed
But there was no **libjsoncpp.so.20.** There was only **libjsoncpp.so** and **libjsoncpp.so.22.**

Is the only way to solve this problem by creating a symbolic link with `ln -s /usr/lib/libjsoncpp.so.22 /usr/lib/libjsoncpp.so.20`?

## Environment:
* Distro (with Version):Arch linux(5.6.6-arch1-1)
* WM:i3-gaps

**Comment by patrick96** [comment]
> Is the only way to solve this problem by creating a symbolic link 

No, don't create a symlink, the libraries have different names because they are potentially not compatible.

Recompiling is the only solution. yay probably didn't recompile polybar because it doesn't know it has to, it just thinks it is up-to-date and just reinstalls the cached package. Either recompile manually or force yay to recompile.
