### ISSUE TITLE
[i3] Per icon color foreground

### ISSUE THREAD

**Issue by M-Gregoire** [polybar/polybar#2083]
## Is your feature request related to a problem? Please describe.
I'd like to have a different color for every workspace icon (i3) in my polybar to get something like:
![2020-05-02-112604_188x26_scrot](https://user-images.githubusercontent.com/9469313/80860445-ed5c7100-8c67-11ea-9f8a-91e88e165e00.png)
 
As far as I know, current settings for the i3 module only allows to specify foreground color for {focused, unfocused, visible, urgent} but couldn't find a way to have a per icon color.

Something like `ws-icon-0-foreground=#FFFFFF` would be awesome.

## Why does polybar need this feature?
This would allow for more customization and beautiful designs!

## Describe the solution you'd like
I've tried passing the color directly in `ws-icon-0` but this doesn't work.

**Comment by M-Gregoire** [comment]
I'm sorry, I completely missed the `%{F#f00}` tag from the documentation!

Thank you for polybar :+1:

**Comment by M-Gregoire** [comment]
I've defined the following in my config:
```
ws-icon-0=1;%{F#AB6712}%{F-}
label-focused-foreground=#7985A3
```

My icon does have the wanted color, however, the `label-focused` is not taken into account when using the workspace.

Is there anyway for the `label-focused-foreground` to take precedence over the icon color as I still want to know which workspace is active.

Otherwise, if it's not, is there anyway to have a smaller underline (Both in width and height): I tried playing with margins and paddings without much success.

Thank you for any help you might provide.

**Comment by patrick96** [comment]
The foreground tag in `ws-icon-0` takes precedence over the label foreground because the custom formatting tags you used are closer to the icon than the formatting tags generated by the label. The format string that the focused label will produce looks something like this:
```
%{#7985A3}%{F#AB6712}%{F-}%{F-}
```

There is no way to have a different color per icon unless when it is in the focused state. I would suggest you use the background color to highlight focused workspaces.
