### ISSUE TITLE
Polybar hangs and systray position

### ISSUE THREAD

**Issue by bdml38** [polybar/polybar#2096]
I'm using polybar with i3, on archlinux, with only 1 bar, on the top of my screen.
At the session login, the systray is at the right of the bar, and it works fine.

Sometimes the bar hangs (nothing is refreshed in the bar). I don't know why yet.
When this happens, if I restart i3 (with the shortcut ($mod+Shift+r restart), polybar restart under the systray.

![systray_polybar_bug](https://user-images.githubusercontent.com/65123473/81852188-ec2a1e80-955a-11ea-91bc-0ee1004b44b4.png)

the apps of the systray are started in i3 config file :
exec --no-startup-id nm-applet
exec --no-startup-id udiskie -ans
exec --no-startup-id pasystray --notify=all
exec --no-startup-id solaar --restart-on-wake-up
exec --no-startup-id pamac-tray

And for transparency I use picom
exec picom -bc

Thanks for help.

**Comment by patrick96** [comment]
Please post your polybar config where this happens as well as the polybar log output.

**Comment by bdml38** [comment]
done...
[polybar.config.txt](https://github.com/polybar/polybar/files/4624726/polybar.config.txt)
[polybar.log](https://github.com/polybar/polybar/files/4624733/polybar.log)

**Comment by bdml38** [comment]
sorry for the number of errors in the log file, I have recently made some tests. I just corrected the temperature problem, and completely removed the demo module.
But the problem of the systray happens before, and very often.

**Comment by patrick96** [comment]
This log file contains messages from 185 runs of polybar. Please post the log messages of a single run of polybar where you see this issue together with the exact config that was used, otherwise it will be very difficult to debug this. In your case that would be the log messages when polybar runs again after reloading i3.

The hanging issue may be due to a long-running program started by polybar. It is a known issue that polybar will wait for any program it started to finish, so when you run for example your browser from polybar, polybar will wait until the browser closes again. The solution to this is to run all commands in the background (add `&` to the command). You already did this in most places but not all of them and I suspect that one of those causes the hanging.

**Comment by bdml38** [comment]
It seems you were right. I have added a "&" to all the processes and the problem has gone.
