### ISSUE TITLE
Typo in binary

### ISSUE THREAD

**Issue by utkarsh2102** [polybar/polybar#2103]
Hi,

While building and maintaining polybar in Debian, the static analyzer tools tell me the following:
`spelling-error-in-binary usr/bin/polybar proces process`

However while trying to grep it, I could find where this is coming from.
Had I known, I would've been happy to raise a PR myself :)

**Comment by patrick96** [comment]
The word `proces` does not appear anywhere in polybar, it only appears in the binary but that may be part of some string loading optimization done by GCC.

It appears as the string:

```
command: Waiting for pid %d to fcommand: Exited with failed statcommand: killed command: Stoppedcommand: Continucommand: Sending SIGTERM to running child procesFailed to open file descriptor
```

This is a bunch of error string put together, with all of them missing parts of the text. I couldn't verify that the message that contains `proces` is actually printed as `process` (as it is specified in the code) because I don't think that path is ever executed, but the other messages are printed correctly even if they don't show up correctly in the binary.

So there is nothing we can do about this, except for maybe telling gcc not to optimize stuff.

Checking spelling errors in `strings` can give you false-positives because `strings` picks up any ASCII sequence of at least 4 characters (even if it isn't actually meant as ASCII)

**Comment by Lomadriel** [comment]
Using `strings /usr/bin/polybar | grep proces`
I found:
```
command: Waiting for pid %d to fcommand: Exited with failed statcommand: killed command: Stoppedcommand: Continucommand: Sending SIGTERM to running child proces
```
But in the code:
https://github.com/polybar/polybar/blob/78b5f88c5f753ff2b364db16d5d38f64d90701dc/src/utils/command.cpp#L55
