### ISSUE TITLE
Bad workspace placement with dual monitor [internal/xworkspaces]

### ISSUE THREAD

**Issue by quenti77** [polybar/polybar#2114]
Hi,

I used i3 and polybar with 2 monitor in a vm.
if i used workspace 1 in left monitor and workspace 2 in right monitor no problem :
*Left mon with ws 1*
![ws_1_left_mon](https://user-images.githubusercontent.com/5288206/83126380-03c7e200-a0d9-11ea-8f0d-2c47852b2481.png)
*Right mon with ws 2*
![ws_2_right_mon](https://user-images.githubusercontent.com/5288206/83126385-0591a580-a0d9-11ea-9b45-13964c3e6b45.png)

But if i go to workspace 3 who show on left monitor i have this in the right monitor :
![ws_3_right_mon](https://user-images.githubusercontent.com/5288206/83126613-5903f380-a0d9-11ea-9eac-e5813e04e063.png)
The workspace 3 is good present on my left monitor but he replace workspace 2 on the right monitor

If i run the workspace 4, the icon for workspace 3 move to left monitor with workspace 1 and workspace 4 is good with workspace 2
*Left mon with ws 1 and 3*
![ws_3_left_mon](https://user-images.githubusercontent.com/5288206/83126930-cd3e9700-a0d9-11ea-8197-38efffe71fbf.png)
*Right mon with ws 2 and 4*
![ws_4_right_mon](https://user-images.githubusercontent.com/5288206/83126933-cf085a80-a0d9-11ea-9e04-7e7367c2595c.png)

If I use internal/i3, I haven't the problem but not show icon and color.

Sorry for my english, is very bad.

**Comment by patrick96** [comment]
Please use the [bug report template](https://github.com/polybar/polybar/issues/new?template=bug_report.md), otherwise we won't be able to help you.

Also consider reading our [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config)

**Comment by quenti77** [comment]
> Please use the [bug report template](https://github.com/polybar/polybar/issues/new?template=bug_report.md), otherwise we won't be able to help you.
> 
> Also consider reading our [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config)

Pourquoi avoir fermer l'issue alors que l'on peut éditer notre message ? C'est un peu con

**Comment by Lomadriel** [comment]
Si tu édites le ticket nous pouvons le ré-ouvrir, mais dans l'état actuel, nous n'avons même pas la config pour essayer de reproduire le bug et par défaut nous fermons les issues invalides.

Même si ton anglais n'est pas très bon, merci d'essayer de l'utiliser, s'il y a des fautes ce n'est pas très important. ;)
-----

If you edit your ticket, we can reopen it, but here, we don't have any means (config, logs...) to reproduce your issue. By default, invalid tickets are closed.

Even if your English is not good, try to use it please, we don't care about mistakes.

**Comment by patrick96** [comment]
Lomadriel is right. The reason we ask people to use the template is because otherwise they might not include information that is important for reproducing the issue (even if they think they included everything that's needed).

In this case the two important pieces of information missing were the polybar version and the config you are using.
I of course could try to reproduce the issue without this information but I could be wasting a lot of time using a different polybar version or different config options to reproduce something that isn't actually reproducible that way.

And this would have been the case here, the bug you experienced in version 3.4.3 is likely already fixed but not yet part of a release. I would have ended up trying to reproduce the issue with a polybar version that already had the fix because I use the latest polybar commit on my machine.

In many cases we already spend more time reproducing an issue than the user spent reporting it, even if they did include all the relevant information and it's probably the most time-consuming part of working on polybar. So I hope you understand why it is important that we have all the information before we try to reproduce and diagnose issues.
