### ISSUE TITLE
[xworkspace] Bad workspace placement with multiple monitor [BUG]

### ISSUE THREAD

**Issue by quenti77** [polybar/polybar#2116]
## Describe the issue
Bad placement if we used xworkspace with multiple monitor

**Expected behavior:**

I used i3 and polybar with 2 monitor in a vm.
if i used workspace 1 in left monitor and workspace 2 in right monitor no problem :
*Left mon with ws 1*
![ws_1_left_mon](https://user-images.githubusercontent.com/5288206/83126380-03c7e200-a0d9-11ea-8f0d-2c47852b2481.png)
*Right mon with ws 2*
![ws_2_right_mon](https://user-images.githubusercontent.com/5288206/83126385-0591a580-a0d9-11ea-9b45-13964c3e6b45.png)

But if i go to workspace 3 who show on left monitor i have this in the right monitor :
![ws_3_right_mon](https://user-images.githubusercontent.com/5288206/83126613-5903f380-a0d9-11ea-9eac-e5813e04e063.png)
The workspace 3 is good present on my left monitor but he replace workspace 2 on the right monitor

If i run the workspace 4, the icon for workspace 3 move to left monitor with workspace 1 and workspace 4 is good with workspace 2
*Left mon with ws 1 and 3*
![ws_3_left_mon](https://user-images.githubusercontent.com/5288206/83126930-cd3e9700-a0d9-11ea-8197-38efffe71fbf.png)
*Right mon with ws 2 and 4*
![ws_4_right_mon](https://user-images.githubusercontent.com/5288206/83126933-cf085a80-a0d9-11ea-9e04-7e7367c2595c.png)

## To Reproduce
Set workspace 1 and 3 to monitor 1 and workspace 2, 4 on monitor right for exemple
Use internal/xworkspaces for the workspace module

## Screenshots
Look problem

## Environment:
* WM: i3
* Distro: xubuntu
* Output of `polybar -vvv`:
```
polybar 3.4.3

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/c++
Compiler flags: -g -O2 -fdebug-prefix-map=/build/polybar-RJo8_n/polybar-3.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wpedantic 
Linker flags: -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now
```

Ma dernière issue était suffisante pour comprendre donc si c'est pas encore bon, vtff et pas la peine de close les issue pour un mauvais format qui en vrai était suffisant pour le bug.

**Comment by patrick96** [comment]
Thanks for using the correct template :)

You still did not include the config with which this issue occurs. But I think there is no need for it in this case because we likely already fixed this bug ;)

I am assuming you are using `pin-workspaces = true`. The xworkspaces module had a lot of issues with assigning workspaces to the right monitor (it was very unpredictable).
I fixed that in #1929 and the fix should appear in the next minor release (3.5.0), for now it is only included if polybar is built directly from this repository from the master branch.

Can you try building polybar from the master branch and see if you still have this issue?
