### ISSUE TITLE
Display percentages of >100

### ISSUE THREAD

**Issue by jfaure** [polybar/polybar#2173]
volume can be boosted past the 100% mark, however %percentage%% caps it at 100

**Comment by patrick96** [comment]
Please post your config. For me it can display percentages over 100 just fine.

**Comment by jfaure** [comment]
```[module/volume]
type = internal/alsa

format-volume = <label-volume>
label-volume =  %percentage%%
label-volume-foreground = ${root.foreground}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground}
label-muted = sound muted```

**Comment by patrick96** [comment]
I was able to reproduce this by increasing the volume through pulseaudio.

The reason this stops at 100% is because the `mixer::get_volume` function in `src/adapters/alsa/mixer.cpp` uses `math_util::percentage` to calculate the percentage and that function clamps the percentage between 0 and 100.

PRs are welcome
