### ISSUE TITLE
Not able to access tray icons

### ISSUE THREAD

**Issue by jedi2610** [polybar/polybar#2189]
The tray icons become blurry sometimes and i'm not able to access them.

**Was it working before?**
no i compiled the latest version and this is the first time i'm using polybar

## Screenshots

![2020-09-28-18-58-27](https://user-images.githubusercontent.com/30691152/94463257-478f3d00-01da-11eb-82d1-86ddab015acd.png)

## Environment:
* WM: i3
* Distro: ubuntu 20.04

**Comment by patrick96** [comment]
Hmm. I have never seen anything like this before. Can you try some other bar with tray support and see if it happens there as well? You could for example try with `stalonetray` (make sure to stop all polybar instances first). Polybar has very little control over the tray icons themselves, each of them is basically its own window managed by whatever application provides that tray icon, that's why I suspect this is some issue with trays in general.

**Comment by danielnehrig** [comment]
@jedi2610 do you have by any chance a compositor running ?

**Comment by jedi2610** [comment]
@danielnehrig yeah, it's compton

**Comment by danielnehrig** [comment]
ignore polybar in the compositor config to not apply blur and try again
