### ISSUE TITLE
Config options for exec args - e.g. `exec-arg-0 = --value foobar`, `exec-arg-1 = -vv`

### ISSUE THREAD

**Issue by OJFord** [polybar/polybar#2207]
## Is your feature request related to a problem? Please describe.
In order to configure script modules similarly to internal ones, they need to take command line arguments. These can get long, making the `exec` line unwieldy and less readable.

## Why does polybar need this feature?
Ease of configuration; encouraging nicely integrated configurable third-party modules.

## Describe the solution you'd like
I would suggest any attribute prefixed `exec-arg` get appended to `exec` (without `'exec-arg'`) with their value if non-empty, so that:
```ini
exec = something
exec-arg--verbose = true
exec-arg-v =
```
becomes:
```
something --verbose=true -v
```

Of course, there will always be exceptions where there's some non-`-`-prefixed arguments and they need to come in a certain order, but I think this would deal with a lot of cases.

**Comment by patrick96** [comment]
I don't see how

```dosini
exec = something
exec-arg--verbose = true
exec-arg-v =
```

is better than

```dosini
exec = something --verbose=true -v
```

If the commandline arguments are so unwieldy, I think the better solution would be to create a shell script that runs the command with all the right comandline arguments and to put that script in the `exec` field.

**Comment by OJFord** [comment]
My real use was marioortizmanero/polybar-pulseaudio-control#34 - arguments to specify the icons and sink names for pulseaudio-control, which easily wraps onto the next line at reasonable editor widths. IMO that configuration belongs in the polybar config, which also avoids every user having to create their own thin wrapper script just to supply their chosen arguments.

Multiline values would be another possible solution - I don't know if polybar's INI parser supports it, I haven't managed to guess a syntax for it that's accepted.

**Comment by patrick96** [comment]
I see your point and I agree that having to create a shell script wrapper for every script module is not ideal.

The config does not support multiline values, but that would indeed be a solution to this problem. I think this could be implemented with something like adding `\` to the end of the line like in bash. However, this would require us to have support for an escape character in the config itself (which we don't), so this isn't as easy to implement as it looks like.

I am not a fan of settings like `exec-args--verbose` because it assumes certain things about the commandline arguments and also because it doesn't support positional arguments (no way to represent `foo --bar baz`).

A syntax I think would work better is the following:

```dosini
exec = cmd
exec-arg-0 = -foo
exec-arg-1 = --bar
exec-arg-2 = baz
```

This would then be executed as `cmd -foo --bar baz`. This is still a bit verbose, we could also just have `exec-0`, etc.

**A note about how to implement this:**

There can still be some complications with this. For example how should we represent `cmd -foo "1 2 3"`?

I see two obvious way:

**1:**
```dosini
exec = cmd
exec-arg-0 = -foo
exec-arg-1 = ""1 2 3""
```

**2:**
```dosini
exec = cmd
exec-arg-0 = -foo
exec-arg-1 = 1 2 3
; exec-arg-1 = "1 2 3"
```

1 is the easiest for us to implement because we can just stitch together everything and pass it to `/bin/sh`. But it is a bit intuitive because you have to use two pair of quotes. The first pair will be removed by the config parser and the second pair are there for the shell because it groups together `1 2 3` into a single argument.

2 is more straightforward for the user (they can use quotes if they want, but don't have to), but less for the implementation. Either we have to parse each argument and properly escape spaces and other special shell characters. We should avoid doing this at all costs because it adds *a lot* of complexity, also different shells may have different characters that need to be escaped. The other alternative would be to not pass the command to `/bin/sh` but directly use the `execv` syscall to execute `cmd` and pass each argument separately.
Both of these approaches would disallow things like `exec-arg-0 = -foo bar` because it would treat `-foo bar` as a single argument.

I would prefer the first option, even though it might look a little ugly, it gives the most control to users.

**Comment by OJFord** [comment]
I moved to wayland (& waybar) some time ago, so just a note that from my perspective this can be closed - seems there's not been any other interest.

**Comment by patrick96** [comment]
I'll close this. There doesn't seem to be a clean way to achieve this anyway.
