### ISSUE TITLE
Bar with override-redirect property will in fullscreen window as it's background 

### ISSUE THREAD

**Issue by akane-sora** [polybar/polybar#2226]
As I turn on the terminal transparency, when alt + f to trigger the window fullscreen mode.
I can see the bar as the terminal background, it didn't overlap, just stay there as a layer.
But the bar without this property, it will disappear, which is I expected.

The reason I use this property is I want to cut the whole bar as 2 separate parts, one in left and the other in right.
Both of them are in a fixed width with a comfortable off-set x for me.
So if I don't use override-redirect for the right one, it will show under the left part as a second line.
May there has another way to do this?

**Comment by patrick96** [comment]
Which WM are you using?

**Comment by akane-sora** [comment]
> Which WM are you using?

i3-gpas

**Comment by patrick96** [comment]
Have you tried [`wm-restack = i3`](https://github.com/polybar/polybar/wiki/Configuration#bar-settings)?

**Comment by akane-sora** [comment]
> Have you tried [`wm-restack = i3`](https://github.com/polybar/polybar/wiki/Configuration#bar-settings)?

sure, but it doesn't help.

**Comment by patrick96** [comment]
Can you post a screenshot of the problem?

**Comment by akane-sora** [comment]
![normal](https://user-images.githubusercontent.com/71393506/97085865-a7023080-1652-11eb-90c0-863675a4ca87.png)
![fullscreen](https://user-images.githubusercontent.com/71393506/97085869-ae293e80-1652-11eb-8534-cb1bef7bdcaf.png)

**Comment by akane-sora** [comment]
like above, the left bar disappear in fullscreen mode.
However the right one still keep the location as a layer.

**Comment by akane-sora** [comment]
Another thing I noticed is my tray seems somehow stop working, you can see the picture didn't contain tray which I have settle in polybar config as

```
tray-position = left
tray-padding = 2
tray-background = #0063ff
tray-detached = false
tray-scale = 1.0
```

**Comment by patrick96** [comment]
What you want to achieve isn't really possible. Your bars disappearing when you go into fullscreen mode is done by i3, in most other WMs, you will still see them. However, i3 doesn't do that if you have `override-redirect = true` (because `override-redirect` tells the WM not to manage the window). That's why only the window without override-redirect disappears.
i3 also doesn't allow you to have two bars next to eachother unless you have `override-redirect = true`.

This means you can get a consistent experience by having `override-redirect = true` on both bars, but you can't have both bars disappear.

I guess it would be possible to hide polybar yourself with [`polybar-msg`](https://github.com/polybar/polybar/wiki/Inter-process-messaging), whenever you go into fullscreen mode.

About the tray issue, this is a known issue (see #425). Havin `override-redirect = true` on the bar with the tray should fix the issue.

**Comment by akane-sora** [comment]
I have added the override-redirect for the tray stayed bar, but I still can't see the tray icon.

Does polybar need any 3rd application for a tray?
