### ISSUE TITLE
Can you update the dependency list for polybar since many of the dependencies are not available on Debian-based distro ?

### ISSUE THREAD

**Issue by Nova-Striker** [polybar/polybar#2239]
## Build Process

The dependencies like `cairo` ,  `libxcb` , ` xcb-util-image` , `xcb-util-wm` are not available on Ubuntu . I cannot even get polybar  installed using `apt` :

![Screenshot from 2020-11-06 13-47-49](https://user-images.githubusercontent.com/64089730/98342634-b449f280-2036-11eb-9137-11862ec44868.png)

The above mentioned dependencies also could not be installed :

![Screenshot from 2020-11-06 13-49-47](https://user-images.githubusercontent.com/64089730/98342836-f96e2480-2036-11eb-846d-456ab981cd17.png)

## Environment:
* Distro (with Version): Ubuntu 20.04

**Comment by Nova-Striker** [comment]
- `cairo` ---> `libcairo2-dev`
- `xcbgen` --->`python3-xcbgen`
- `libxcb` -----> `libxcb1-dev`
- `xcb-util-image` ---> `libxcb-image0-dev`
- `xcb-util-wm` ---> `libxcb-util0-dev`

**Comment by patrick96** [comment]
We don't have the package name for every dependency on every distro in the README because it would take up too much space.
But we do already have an exhaustive list of packages for debian based distros, fedora and openSUSE on the [wiki](https://github.com/polybar/polybar/wiki/Compiling#dependencies-1).
