### ISSUE TITLE
Polybar stopped showing after update (bspwm && aur)

### ISSUE THREAD

**Issue by guidiamond** [polybar/polybar#2267]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

After updating from aur repo, polybar stopped showing up when i launch it.
**Expected behavior:**

Before updates everything was doing just fine and i haven't changed a single line of my current cfg.

**Actual behavior:**

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
* If no, what was the last version where this worked correctly?

## To Reproduce

```dosini
git clone https://github.com/guidiamond/dotfiles/blob/master/.config/polybar/
./polybar/launch.sh
```

## Polybar Log

```
xrandr is /usr/bin/xrandr
notice: Parsing config file: /home/damndiamond/.config/polybar/config.ini
error: /home/damndiamond/.config/polybar/config.ini:49: Section name 'bar/main.top.right' is empty or contains forbidden characters.
notice: Parsing config file: /home/damndiamond/.config/polybar/config.ini
error: /home/damndiamond/.config/polybar/config.ini:49: Section name 'bar/main.top.right' is empty or contains forbidden characters.
```

## Environment:
* WM: bspwm
* Distro: arch
* Output of `polybar -vvv`:

```
polybar 3.5.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

## Additional context

The error showed after update is different then before.

**Comment by estw272** [comment]
Same problem on arch with i3. Reinstalling / rebuilding didn't help.

Not sure it it's connected, but `polybar reload` shows this error:

`Key name 'format.foreground' is empty or contains forbidden characters.`
The line in question looks like this
`format.foreground = ${colors.foreground}`
and didn't change for a long time.

**Comment by patrick96** [comment]
With 3.5.0, we introduced some new rules for section and key names in the configuration. In particular, the following characters and spaces are no longer allowed: `"'=;#[](){}:.$\%`.

In your case, the period(s) in your header and key are causing the issue. The reason periods are no longer allowed is because it is impossible to use `${...}` references when the header or key uses a period. For example `${bar/main.top.right.background}` can be interpreted in many ways, the section to use could be `bar/main`, or `bar/main.top`, etc.

@guidiamond You will unfortunately need to change the name of your bars. I would recommend something like `bar/main-top-right`.

@estw272 The key `format.foreground` is probably never used in your config (unless you explicitly reference it with `${...}`). The correct name for that key would be `format-foreground`, so either rename it to that or remove the line altogether.
