### ISSUE TITLE
[Bug] Polybar ignores inheritance lists / multiple inheritance

### ISSUE THREAD

**Issue by Adk9p** [polybar/polybar#2269]
## Checklist

* [X] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

# Describe the bug

polybar ignores inheritance lists / multiple inheritance
after updating polybar from 3.4.3 to 3.5.0

**Expected behavior:**

polybar inherits from each section in the list

**Actual behavior:**

polybar ignores list as if it doesn't exist

**Was it working before?** 
yes
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)?
nope
* If no, what was the last version where this worked correctly?
for me, 3.4.3

## To Reproduce

```dosini
[inherit_me]
	modules-left   = i3

[bar/main]
	; works
	; inherit = inherit_me 

	; doesn't
	inherit-0 = inherit_me

[module/i3]
	type = internal/i3
```

## Polybar Log

```log
notice: Parsing config file: mvp.ini
error: No modules created
```

## Environment:
* WM: i3
* Distro: Archlinux
* Output of `polybar -vvv`:

```
polybar 3.5.0

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/sbin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 
```

**Comment by patrick96** [comment]
That's odd. Polybar never had inheritance lists or multiple inheritance. I will investigate, thanks for letting me know.

**Comment by patrick96** [comment]
This is very interesting indeed. When trying to do inheritance, polybar used to try all keys that started with `inherit` instead of just keys that exactly matched `inherit`.

When I rewrote parts of the config system, I thought that was just an oversight, a bug even, I didn't realize that it could be used for multiple inheritance and I don't think it was ever intended that way (this functionality was never documented).

What I will do now is I will add back this bug/feature and immediately print a deprecation warning for it. I will also add properly defined multiple inheritance by allowing multiple sections to be specified in the `inherit` key.

The reason why we can't really have multiple inheritance using multiple `inheritance*` keys is because it has a different behavior depending on the order inherited keys are copied.
If you inherit from multiple sections and some of the sections define the same key, the value you get for that key depends on which section is inherited first.
In polybar, the order of your keys inside a section never matters and I don't think it makes sense to change this for the inherit keys. Having `inherit = section1 section2 section3` is also much cleaner and less verbose in my opinion.

**Comment by patrick96** [comment]
Fixed in #2271 

I'll try to release 3.5.1, which will contain this fix, in a few days.

**Comment by Adk9p** [comment]
wow! thanks for the quick response and turn around.
I don't know how I started using the inheritance lists, I assume trial and error and it just worked. Never gave it another thought.

I agree the space separated list does look better and im glad it's going to be a supported feature now since it's useful for organizing the config; comments work but I prefer using named sections :p 

Thanks again for all the time and effort you put into polybar :)

**Comment by patrick96** [comment]
You're welcome :)

The unfortunate problem with trial-and-error is that sometimes you start to rely on quirks in polybar that are not really part of its functionality and also not documented anywhere and some of these quirks are very likely to be removed/changed between updates.
