### ISSUE TITLE
backlight module is "delayed"

### ISSUE THREAD

**Issue by binex-dsk** [polybar/polybar#2367]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

With the backlight module, the brightness bar is "delayed". I.e. when I first change it, the bar doesn't change, and when I change it again, the bar changes to what it was before the current change.
**Expected behavior:**

Backlight label/bar should change when brightness is changed

**Actual behavior:**

Delayed behaviour explained before

**Was it working before?**
* Did you also experience this bug in an earlier version of polybar (yes/no/don't know)? no
* If no, what was the last version where this worked correctly? None, I just installed it

## To Reproduce

```dosini
[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = amdgpu_bl0

label = %percentage%% brightness
interval = 5
```

Change your brightness with something like this in your i3 config:
```
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl s +5%
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl s 5%-
```

Must have `brightnessctl` installed. You can also just `brightnessctl s +5%` or `brightnessctl s 5%-`.

## Polybar Log

```
notice: Parsing config file: /home/swirl/.config/polybar/config
error: Disabling module "bspwm" (reason: Could not find socket: /tmp/bspwm_0_0-socket)
error: module/mpd: Connection refused
notice: pulseaudio: using default sink alsa_output.pci-0000_03_00.6.analog-stereo
error: module/mpd: Connection refused
notice: Loaded font "fixed:pixelsize=10" (name=Nimbus Sans, offset=1, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)
notice: Loaded font "unifont:fontformat=truetype:size=8:antialias=false" (name=Droid Sans, offset=0, file=/usr/share/fonts/droid/DroidSans.ttf)
notice: Loaded font "siji:pixelsize=10" (name=Nimbus Sans, offset=1, file=/usr/share/fonts/gsfonts/NimbusSans-Regular.otf)
warn: Systray selection already managed (window=0x1200009)
```

## Environment:
* WM: i3-gaps
* Distro: Artix Linux
* Output of `polybar -vvv`:

```
polybar 3.5.4

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
We had this problem before in #1180 and we fixed it. But I think in your system configuration, this may not be fixable.

Polybar reads from files in `/sys/class/backlight/amdgpu_bl0/` to get the brightness data. People reported that when polybar was reading from the `brightness` file, it lagged behind one step (just as you are reporting), the fix was to read from `actual_brightness` where we didn't experience that problem.

But, in #1870 it was reported that on systems with an `amdgpu` backlight, the `actual_brigthness` file contains unexpected values, that's why for `amdgpu` backlights, we switch back to reading the `brightness` file. So the fix for the original issue likely doesn't work on your system.

Can you set your brightness to 100% and then post the contents of the following three files:

* `/sys/class/backlight/amdgpu_bl0/brightness`
* `/sys/class/backlight/amdgpu_bl0/actual_brightness`
* `/sys/class/backlight/amdgpu_bl0/max_brightness`

If for some reason your backlight has the correct values in `actual_brigthness`, it may be possible to let the user choose between the `brightness` and `actual_brightness` file. If not, the only way to fix this, is to figure out why the `brightness` is not updated immediately and fix it (which I am not sure is possible).

I don't think I have ever experienced the delayed update issue myself and I don't have access to any system with and amdgpu backlight. So, I can't really try fixing this.

**Comment by binex-dsk** [comment]
All are `255`.

Interestingly, when I `cat`ted any of them, the bar updates. It also updates if I do `xbacklight -display eDP -get`. Maybe it's just reading the value too quick or something?

**Comment by binex-dsk** [comment]
Okay, oddly enough, I tried using `xbacklight` (from the `acpilight` package, regular `xorg-xbacklight` doesn't work for me) to change the brightness and now it's not delayed at all, so I guess that solves that.

But because this occurs with `brightnessctl`, I'll keep this open for now.

**Comment by patrick96** [comment]
> Interestingly, when I catted any of them, the bar updates. It also updates if I do xbacklight -display eDP -get. Maybe it's just reading the value too quick or something?

Yes, `cat`ing the file was also something that triggered an update for other people when this was first reported. I'm not really sure how polybar can read the value too quickly as the module only updates after the file has changed, so it should read the new value, but we still haven't figured out why it doesn't.

> All are 255.

That means that the `actual_brightness` file contains the correct values. I think the solution for this is to give the user the option to choose which files they want to read. For example an option `use-actual-brightness` that defaults to true (except for when the card starts with `amdgpu_bl`) that determines whether `actual_brightness` or `brightness` is used.

PRs are welcome. I'll mark this as "good first issue".

**Comment by binex-dsk** [comment]
yeah that might work. If I feel like it I might try adding it later today

**Comment by patrick96** [comment]
Awesome! :tada:
