### ISSUE TITLE
[feature request] provide generic configuration for first time users

### ISSUE THREAD

**Issue by samueloph** [polybar/polybar#2405]
## Is your feature request related to a problem? Please describe.
First time users of polybar might have difficulty in generating a config file that works for them, especially if they are not compiling it themselves. The implications of this is that polybar could lose possible users because they didn't want to perform the "extra" task of configuring polybar; either because they didn't have time, or because they just wanted to try it out and commit to personalizing the config later.

We briefly discussed this on https://github.com/polybar/polybar/issues/2016#issuecomment-589976084 and so I'm opening this issue to track this specific feature request.

## Why does polybar need this feature?
To lower the friction for polybar adoption and make it easier for first timers to try it out. This would make polybar even with its competitors like i3status (which has a working default configuration).

## Describe the solution you'd like
The issues related to having a generic configuration can be classified into two categories:
1) Depends on something being installed in the system, eg.: fonts
 This issue could be solved by compromising for some value that is generic enough, or that could be easily installed on the system, in such way that packagers could make this a dependency of the package, and that it could be written in polybar's userguide/readme for users wanting the default config.
 
 2) Hardcoded values based on the hardware
  Somethings like battery name and network card IDs needs to be hardcoded into polybar's configuration.
  This could be addressed by an abstraction at the configuration level, having polybar perform the translation to a specific resource ID/name at runtime. I reckon this would be the biggest challenge in this FR.
  Another alternative would be to skip this info altogether on the default configuration, although this will probably degrade the user experience too much as crucial information could be missing from the bar. 

## Describe alternatives you've considered
To provide a script that autogenerates the configuration for the user without needing the install the build dependencies, such that it could be automatically run on the system when the user installs polybar's package (or on the first start).
This would also be a good solution, but I think the other one proposed is better as it would also simplify the configuration file in general.

## Additional context
I understand what I'm asking here might not be doable due to the complexity of abstracting the configuration to that level, and so the alternative solution would be good enough.
I won't be able to submit a PR for this due to time constraints but I can try helping on the design of the solution if needed.

Thanks for working on polybar :)

**Comment by patrick96** [comment]
Thanks for the writeup.

I agree that the long term goal should be for modules to auto-detect certain HW parameters on startup if none are specified in the config (network interface, temperature sensors, backlight provider, battery adaptor).

Version 3.6 will already get this for the network module (#2025). But for others this would still need to be done.

For fonts, a default config should not use any non-standard glyphs (so no font icons). And maybe a way to select a generic monospaced font (like i3 does).
I don't think we can write a portable config that uses font icons because the font names are different among distros and even glyphs may be placed at different positions (maybe depending on the version).

Concrete steps that need to be taken:

* Auto-detect a sensible default for the following modules:
  * backlight
  * battery
  * fs maybe. (Or just alway display the root fs in the default configuration)
  * temperature. This can get tricky.
* Write a nice default configuration that works on all system (using auto-detection features and a monospaced font) and doesn't use font icons.
* Ship the default configuration in `/etc/xdg/polybar/config.ini`
* Support loading the config from `$XDG_CONFIG_DIRS/polybar/config.ini` by default (lowest priority). (see #2016)

I think once we can auto-detect providers for the backlight and battery, we can have a decent default config to ship with polybar.

Even now with auto-detection of network interfaces, we can have a quite full-featured config for desktop machines (which often don't have backlights).

**Comment by parmort** [comment]
For the fonts, we can just use the default `monospace` font. It's fairly easy to customize (see [my dotfiles](https://github.com/parmort/dotfiles/blob/master/fontconfig/.config/fontconfig/fonts.conf)) and is sensible.

We might be able to take advantage of configuration inheritance here with the more hardware-agnostic values? I haven't read up on config inheritance, but that might strike a good balance between frictionless-ness and configuration?

**Comment by patrick96** [comment]
> For the fonts, we could use the default monospace font

That is a very good idea; even if people don't customize it.

> We might be able to take advantage of configuration inheritance here with the more hardware-agnostic values?

So, you mean have a central place where all hardware specific settings are stored. For example a section that defines the network interfaces, battery adapters, etc?

**Comment by parmort** [comment]
Yeah, that could make customizing the necessary values easier without having to scroll through the entire file editing specific lines, which would help new users get started.
