### ISSUE TITLE
Polybar crashes when the system wakes up from sleep

### ISSUE THREAD

**Issue by zypangpang** [polybar/polybar#2418]
## Checklist

* [x] I have read the appropriate section in the [contributing
  guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
* [x] I believe this issue is a problem with polybar itself and not a misconfiguration on my part.
* [x] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that
  may have already reported this problem.
* [x] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.

## Describe the bug

Polybar disappears whenever the system wakes up from sleep. I have to start it manually every time I sleep my laptop.
**Expected behavior:**

Polybar works as it is before system sleeps.

**Actual behavior:**

Polybar exits or crashes.

**Was it working before?**
Yes. It works seamlessly before. The behavior came up after I upgraded my Gentoo system. I think it might be caused by newer version of Xorg server or i3.
## To Reproduce
Sleep the system and then wake it up.

See the attachment file for polybar configs.

## Polybar Log

Below is only the error log. See the attachment file for full log.
```
polybar|notice:  randr_screen_change_notify (2160x1440)... reloading
polybar|notice:  Termination signal received, shutting down...
polybar|warn:  module/i3: Attempting to reconnect socket (reason: Unexpected EOF while reading header)
polybar|notice:  Parsing config file: /home/zypang/.config/polybar/config
polybar|error: No monitors found
```

## Environment:
* WM: i3-4.18 xorg-server-1.20.11
* Distro: Gentoo
* Output of `polybar -vvv`:

```
polybar 3.5.5

Features: +alsa -curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Gentoo
Compiler: /usr/bin/x86_64-pc-linux-gnu-g++
Compiler flags: -march=native -O2 -pipe -Wall -Wextra -Wpedantic
Linker flags: -Wl,-O1 -Wl,--as-needed
```

## Additional context

[polybar-error.log](https://github.com/polybar/polybar/files/6390165/polybar-error.log)
[config.txt](https://github.com/polybar/polybar/files/6390173/config.txt)

**Comment by patrick96** [comment]
Hmm, so what seems to happen is that polybar detects a change in the monitor configuration and because of `screenchange-reload = true`, polybar restarts.

When starting up again, polybar can't detect any connected monitors at all in the system and thus fails to start.

Obviously the laptop screen is connected, so somehow polybar thinks there are no monitors.

Could you run the `xrandr` command directly before starting polybar in your startup routine and also redirect its output to the log file. This will tell us whether xrandr also reports that no monitors are connected (in which case this will not be a bug in polybar).

**Comment by zypangpang** [comment]
I add xrandr to the resuming script and redirect its output to a file. The result shows that when the system wakes up, xrandr command outputs nothing. It seems this is not a bug of polybar. It might relates to X11 window system or Gentoo elogind resuming process. I disabled screenchange-reload config option as a temporary workaround. Hope later system upgrade can solve the problem. Thanks anyway.

**Comment by farhaven** [comment]
I'm seeing the same problem. For the record, FVWM3 used to be [similarly affected](https://github.com/fvwmorg/fvwm3/pull/789). There, the solution was to just not treat zero active monitors reported by `XRRGetMonitors` as an error. Maybe something similar works for Polybar as well (i.e. don't restart if XRandR tells us no screens are connected)?

For context, this happens when I close my laptop's lid without any external screens connected. The display is turned off first, which causes `XRRGetMonitors` to return 0 (since no active monitors are connected), and the laptop only suspends after that. In that short window, Polybar decides to quit because no screens could be detected.

If y'all are OK with that, I can prepare a PR.

**Comment by patrick96** [comment]
I think that's a good solution. A PR is welcome. The logic for this probably neatly fits into the `void screen::handle(const evt::randr_screen_change_notify& evt)` method in `screen.cpp`
