### ISSUE TITLE
Scrot -s option not being parsed in script module

### ISSUE THREAD

**Issue by kawaki-san** [polybar/polybar#2447]
I have 2 bash scripts for screenshots.
`screenshot.sh`
```sh
#!/bin/bash
dateTime=$(date '+%Y%m%d%H%M%S')
mkdir -p $HOME/'Pictures/Screenshots'
scrot -q 100 $HOME/'Pictures/Screenshots/'$dateTime'.png'
notify-send -i $HOME/'Pictures/Screenshots/'$dateTime'.png' "Captured" "Screenshot saved at "$dateTime'.png'
```

And `screenshot-region` for capturing a region
```sh
#!/bin/bash
dateTime=$(date '+%Y%m%d%H%M%S')
mkdir -p $HOME/'Pictures/Screenshots'
scrot -s -q 100 $HOME/'Pictures/Screenshots/'$dateTime'.png'
notify-send -i $HOME/'Pictures/Screenshots/'$dateTime'.png' "Screenshot captured!" "Screenshot saved at "$dateTime'.png
```
Both work as intended when executed from my terminal. When I map them to my `screenshot` module, the first one works fine, but `screenshot-region` does not. The `scrot` command does not execute.

This is my module:
```
[module/screenshot]
type = custom/script
exec = echo "%{T2}%{T-}" &
format = "%{F#da294f}<label>%{F-}"
click-left = ~/.config/sxhkd/scripts/screenshot-region.sh
click-right = ~/.config/sxhkd/scripts/screenshot.sh
tail = true
```

The log doesn't output anything, just loads my fonts.

Am I missing something?

**Comment by patrick96** [comment]
Someone else did have that exact issue on reddit a few months ago: https://www.reddit.com/r/Polybar/comments/kewmc5/scrot_from_polybar/

The solution was to add a small delay to the script.

I don't really know why this works, I can only speculate that maybe since it is started as a result of a click, the mouse pointer is somehow still locked and scrot can't grab it.

Let me know if this also works for you.

**Comment by kawaki-san** [comment]
It works. Thanks.
