### ISSUE TITLE
start script dont work with bspwm after boot

### ISSUE THREAD

**Issue by icf20** [polybar/polybar#2457]
i followed the wiki so there is no issues on the start script

## Describe the bug

start script dont work with bspwm after boot but if i exit bspwm and i log in again it works, maybe BSPWM issue?

## Polybar Log

```
---
polybar|notice:  Parsing config file: /home/user/.config/polybar/config

```

* Output of `polybar -vvv`:

```
polybar -vvv                            
polybar 3.5.5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now 

```

**Comment by patrick96** [comment]
What exactly doesn't work? The log you posted suggests polybar is running.

**Comment by icf20** [comment]
Well the polybar dont show up on screen, but i change the kernel is working

**Comment by darkelectron** [comment]
Try restarting polybar or re-running the _launch script_. That way you don't have to log out.

**Comment by patrick96** [comment]
@icf20 That is weird. I'm not sure how much the kernel version has to do with this. Normally it's just a timing issue where polybar starts before the WM and you get some unexpected behavior.

You could try to do a delayed launch by just adding a short `sleep` command before your launch script.

**Comment by icf20** [comment]
@patrick96 current script

```
#!/usr/bin/env bash
sleep 2
# Terminate already running bar instances
```

**Comment by patrick96** [comment]
@icf20 I think you are missing some of the script ;)

Does this work for you now?

**Comment by icf20** [comment]
> @icf20 I think you are missing some of the script ;)
> 
> Does this work for you now?

i posted that because was the delay part 

1) i had that for weeks and dint help but on LTS kernel it did work

2) on my last boot on 5.13.12 kernel i added a +3 sec delay after the bar to pywal and it did show up after login  (5 sec pywal delay - 2 sec delay polybar=3)

**Comment by patrick96** [comment]
Alright, let's approach this a bit more systematically

* When you run your launch script after bspwm has finished starting up, does polybar show up then?
* I didn't notice this before, but during normal startup, polybar should print at least one more line, specifying which fonts it loaded. So either there was some issue with collecting the logs or polybar gets stuck while starting up. When you are using the version where polybar doesn't start, please run polybar with trace logging `-l trace`. This will print a lot more logging information and should tell us more precisely where polybar is stuck
* The interaction with pywal could maybe explain this. I think there was another issue with polybar freezing because of pywal. Does your pywal setup reload polybar?

Maybe also post your config, just so that we're on the same page.

**Comment by icf20** [comment]
> Does your pywal setup reload polybar?

Before when it worked properly it dint reload, polybar loaded the colour pywal generated

under the current setup (delayed) polybar starts black and then it reloads using pywal colours

**Comment by patrick96** [comment]
> under the current setup (delayed) polybar starts black and then it reloads using pywal colours

That is probably expected. I remember that the example pywal uses for its polybar configuration uses the same fallback color for everything (background and text color) so if pywal didn't setup anything yet, polybar will likely fall back.

**Comment by icf20** [comment]
i still dont find the explication why it worked on some kernels and others dint 


if anyone comes from google i hope all this helps
