### ISSUE TITLE
Rework command enqueing to minimize swallowing

### ISSUE THREAD

**Issue by Astrono2** [polybar/polybar#2469]
## Is your feature request related to a problem? Please describe.

It is currently not possible to call `m_sig.emit(button_press{*});` more than once before `m_inputdata` is cleared in the next iteration of the eventqueue worker loop. This is a problem, for example, if more than one action need to be triggered in the same method call.

## Why does polybar need this feature?

This feature would make the core system underlying polybar considerably more flexible, and would allow for easier and faster implementation of some features.

## Describe the solution you'd like

Instead of `m_inputdata` there could be a queue of input data strings.

## Describe alternatives you've considered

One alternative is to not emit many signals one after the other, and instead store the signals and call them after a short delay, but this increases complexity and makes everything more prone to bugs.

## Additional context

![image](https://user-images.githubusercontent.com/8162008/125780090-7b0d10b0-8471-4562-b3a4-b2598db70129.png)
Results in
![image](https://user-images.githubusercontent.com/8162008/125780201-95eeffa0-449f-4780-9d3b-726fb3e72f68.png)

**Comment by madhavpcm** [comment]
Hello I am new to polybar, I would like to contribute to this issue, is there any place where I could start?

**Comment by patrick96** [comment]
@madhavpcm Yes, the pending action string is stored in `inputdata` in `notifications_t` in `controller.hpp`. Making that a queue would probably be the most straightforward way to solve this.

Thanks :)

**Comment by madhavpcm** [comment]
I have did some changes to  `notifier_handler()` and `trigger_action()` as these were the places where I noticed enqueuing and dequeuing takes place. I believe the `notifier_handler()` loop runs separately and checks if `inputdata` is available and call `process_inputdata()`. However, in order to test I'm confused not sure how to try out `m_sig.emit(button_press{*})` multiple times

**Comment by patrick96** [comment]
Yeah testing might be tricky here since it relies on the button clicks (or ipc actions) arriving very quickly after each other. I don't think there is a way to trigger this by hand.

I also don't think you can write any automated tests for this since the controller relies on an X server running which we can't handle yet in our testing infrastructure.

But if you want to just quickly verify things work for you, you could add something like this:

```cpp
m_loop->timer_handle([this]() { trigger_action("notify-send A"); trigger_action("notify-send B"); })->start(500, 0);
```

This will trigger two actions directly after one another (they should each create a notification popup) after about half a second. Add this line directly before we set `m_loop_ready` to `true`.

**Comment by madhavpcm** [comment]
![image](https://user-images.githubusercontent.com/59736487/135715266-095239b7-2b6d-4173-a652-f05b1ef4c326.png)
I hope this is the desired behaviour

**Comment by patrick96** [comment]
Yes, that looks alright :)

**Comment by madhavpcm** [comment]
Im terribly sorry for the messy commits in the PR, I keep forgetting one thing or the other before committing. Kind of a beginner with git and pull requests. Thanks alot for the help!

**Comment by patrick96** [comment]
Don't worry about that one bit. That's why we have PR reviews and formatting tools ;)

I appreciate the effort

**Comment by madhavpcm** [comment]
Thanks Alot! I will work on my approach, looking forward to contribute more in the near future :).
