### ISSUE TITLE
[Bug]: Improve IPC hook protocol 

### ISSUE THREAD

**Issue by dvermd** [polybar/polybar#2532]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

`polybar-msg hook demo 11`

### Minimal config

```dosini
[bar/bar_test]
enable-ipc = true

modules-center = demo demo1

[module/demo]
type = custom/ipc
hook-0 = echo hook0
hook-1 = echo hook1
hook-2 = echo hook2
hook-3 = echo hook3
hook-4 = echo hook4
hook-5 = echo hook5
hook-6 = echo hook6
hook-7 = echo hook7
hook-8 = echo hook8
hook-9 = echo hook9
hook-10 = echo hook10

[module/demo1]
type = custom/ipc
hook-0 = echo hook0
hook-1 = echo hook1
hook-2 = echo hook2
```

### Expected behavior

Only the hook of the `demo` module is triggered

### Actual behavior

Given the way the hook message is serialized before being send to polybar : `hook:module/<module_name><hook_index>`, polybar receives `hook:module/demo11` that will match:
* `module/demo hook 11`
* `module/demo1 hook 1`

This means both hooks are triggered and the 2 modules are updated.

### Window Manager and Version

i3-gaps 4.19.1

### Linux Distribution

Manjaro Linux 21.1.5

### Polybar version

```text
polybar 3.5.5

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/bin/c++
Compiler flags: -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wall -Wextra -Wpedantic -O3 -DNDEBUG
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
```

**Comment by patrick96** [comment]
Thanks for pointing this out. I always suspected there would be some ambiguity there.

Unfortunately we can't really change the serialization format sent to the named pipe in `/tmp` because that would be a breaking change since people can use it without using `polybar-msg`.

However, there are already multiple solutions for this in the pipeline (though all of them will come out in 3.6.0 and not in a bugfix release).

For one, there will be a `hook` module action where the module name and the hook id are properly separated (see #2528).

In addition, the hook part of the IPC protocol will be deprecated in favor of these new module actions.

And finally, `polybar-msg` will be using a new message format and will start using a socket instead of a named pipe (#see 2504).
This also deprecates the direct use of the serialzation format and the named pipe and the only valid way to send IPC messages to polybar will be `polybar-msg`.
