### ISSUE TITLE
[Bug]: xwindow title doesn't update when switching to empty workspace

### ISSUE THREAD

**Issue by rien333** [polybar/polybar#2637]
### Checklist

- [x] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

1. Add both the xwindow and bspwm modules to your bar.
(you actually need both in my experience, even though the problem seems to be with xwindow)
3. Add one of the aestethics related `label-*` settings under `[module/bspwm]`, e.g. `label-focused-padding` or  `label-focused-background`. 
 **This step is important**: just having `type = internal/bspwm` works fine
4. With polybar running, focus on a window (say `Window X`).
5.  Switch to an empty workspace.

Now the title of `Window X` should still be visible in the bar, even though it's not the focused window. In other words, polybar  "ignores" the fact that there's no longer any focused window, and acts as if the previously focused window was still active  (see logs). It's not perfectly consistent, but happens like 90% of the time.

### Minimal config

```dosini
[module/title]
type = internal/xwindow

[module/bspwm]
type = internal/bspwm
label-focused-foreground = #2e3440

[bar/example]
modules-left = bspwm title
```

### Polybar log

```text
This is polybar right _after_ I switch to an empty workspace, followed by me switching back. 

* module/bspwm: Parsing socket data: MeDP1:o1:o2:f3:f4:f5:f6:f7:F8:o9:LT
* module/bspwm: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=165x24+0+0, falloff=0)
* module/bspwm: Parsing socket data: MeDP1:o1:o2:f3:f4:f5:f6:f7:f8:O9:LT:TT:G
* module/bspwm: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=165x24+0+0, falloff=0)
* module/title: Rebuilding cache
- bar: Ignoring update (unchanged)
```

### Expected behavior

When on an empty workspace, polybar should always display the value of `label-empty`, which by default is the empty string.

### Actual behavior

With the config above, polybar often doesn't update the window title when switching to an empty workspace. Rather, it just shows the title of the previously active window. The module does finally update if you move the mouse over the xwindow module. 

### Window Manager and Version

bspwm 0.9.10

### Linux Distribution

Arch Linux

### Polybar version

```text
polybar 3.6.1

Features: +alsa +curl +i3 +mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /usr/lib/ccache/bin/c++
Compiler flags: -march=skylake -O2 -pipe -fno-stack-protector -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

### Additional Context / Screenshots

I think this is a recent thing? Perhaps introduced between 3.5 and 3.6? (I've been using the AUR packages, and have been seeing this for like the past 1-2 weeks)

**Comment by patrick96** [comment]
Thanks for reporting :)

This sounds like a regression in 3.6 (which has been released 12 days before you opened this issue). Though this is peculiar because the xwindow module itself barely changed since 3.5.

Are you comfortable compiling polybar from source with some debugging patches added on?
If so, please add the following patch and run polybar again:

```patch
diff --git a/src/modules/xwindow.cpp b/src/modules/xwindow.cpp
index 80383ce3..2b98c964 100644
--- a/src/modules/xwindow.cpp
+++ b/src/modules/xwindow.cpp
@@ -83,6 +83,7 @@ namespace modules {
    * Handler for XCB_PROPERTY_NOTIFY events
    */
   void xwindow_module::handle(const evt::property_notify& evt) {
+    m_log.notice("%s: property_notify: %s", name(), m_connection.get_atom_name(evt->atom).name());
     if (evt->atom == _NET_ACTIVE_WINDOW) {
       update(true);
     } else if (evt->atom == _NET_CURRENT_DESKTOP) {
@@ -113,10 +114,12 @@ namespace modules {
     }
 
     if (m_active) {
+      m_log.notice("%s: active: %s", name(), m_active->title());
       m_label = m_statelabels.at(state::ACTIVE)->clone();
       m_label->reset_tokens();
       m_label->replace_token("%title%", m_active->title());
     } else {
+      m_log.notice("%s: no active window", name());
       m_label = m_statelabels.at(state::EMPTY)->clone();
     }
   }
```

This reports exactly what kind of events the module receives and what it detects as the current window. I'm suspecting this has something to do with events not arriving at the module.


Please again indicate in the log right before you switch to an empty workspace and right before you switch back.

**Comment by rien333** [comment]
Thank you so much for looking into this! It's a small thing, but it can be distracting :) I'm more than comfortable building from source, I'll do so later today.

**Comment by rien333** [comment]
Sorry for the huge delay. I'm not sure if this is interesting, but this is the log.  The bees are my comments.

```
🐝  (default) this is when I'm focusing a window on filled workspace A

notice: module/title: property_notify: _NET_ACTIVE_WINDOW
notice: module/title: active: ~
notice: module/title: property_notify: _NET_CLIENT_LIST_STACKING
* module/title: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=106x24+0+0, falloff=0)
notice: module/title: property_notify: _NET_ACTIVE_WINDOW
notice: module/title: active: polybar --log=trace ~/.c/polybar
notice: module/title: property_notify: _NET_CLIENT_LIST_STACKING
* module/title: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=304x24+0+0, falloff=0)

🐝 (before switch) typing this right _before_ I switch to empty workspace B

* module/bspwm: Parsing socket data: MeDP1:o1:o2:o3:o4:f5:f6:f7:F8:o9:LT
* module/bspwm: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=304x24+0+0, falloff=0)
* module/bspwm: Parsing socket data: MeDP1:o1:o2:o3:o4:f5:f6:f7:f8:O9:LT:TT:G
notice: module/title: property_notify: WM_STATE
notice: module/title: property_notify: _NET_CURRENT_DESKTOP
notice: module/title: active: polybar --log=trace ~/.c/polybar
notice: module/title: property_notify: _NET_ACTIVE_WINDOW
notice: module/title: active: polybar --log=trace ~/.c/polybar
notice: module/title: property_notify: WM_STATE
notice: module/title: property_notify: _NET_CURRENT_DESKTOP
notice: module/title: active: polybar --log=trace ~/.c/polybar
notice: module/title: property_notify: _NET_ACTIVE_WINDOW
notice: module/title: active: polybar --log=trace ~/.c/polybar
notice: module/title: property_notify: _NET_CLIENT_LIST_STACKING
* module/bspwm: Rebuilding cache
* module/title: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=304x24+0+0, falloff=0)
notice: Received signal(2): Interrupt
* Eventloop finished
notice: Termination signal received, shutting down...
- controller: Detach signal receiver
- controller: Stop modules
* module/bspwm: Disconnecting from socket
* module/bspwm: Stopping
- module/bspwm: Release sleep lock
* Deconstruction of module/bspwm took 0 ms.
* module/title: Stopping
- module/title: Release sleep lock
* Deconstruction of module/title took 0 ms.
- module/bspwm: Deconstructing
- module/title: Deconstructing
* Waiting for spawned processes to end
* Reached end of application...
```

**Comment by patrick96** [comment]
```
🐝 (before switch) typing this right _before_ I switch to empty workspace B

* module/bspwm: Parsing socket data: MeDP1:o1:o2:o3:o4:f5:f6:f7:F8:o9:LT
* module/bspwm: Rebuilding cache
* Redrawing bar window
- renderer: flush(1 geom=304x24+0+0, falloff=0)
* module/bspwm: Parsing socket data: MeDP1:o1:o2:o3:o4:f5:f6:f7:f8:O9:LT:TT:G
```

Did you switch back here? Because first, the bspwm module reports that you are on desktop 8, which is free (`F8`) and afterwards it reports that you are on desktop 9 which is occupied (`O9`).

If that is the case, then for some reason the xwindow module doesn't receive any of the events from the X server that would tell it that the active window has changed.

There must be some kind of weird interaction with the bspwm module here. Maybe some concurrency issue where the bspwm module somehow temporarily prevents us from receiving X events.

**Comment by patrick96** [comment]
This is the strangest thing. I was able to reproduce this locally, kinda. For me, what happens is that when switching from an empty workspace to an occupied one, the xwindow module stays empty.

I have tracked it down to the following:

* Polybar doesn't receive the appropriate X event for `_NET_ACTIVE_WINDOW` at all
* bspwm does correctly send the events though
* This only happens because/when the bspwm module triggers a render cycle because the bspwm module receives the workspace update before polybar is supposed to receive the X event.
* The bspwm module only triggers a render cycle if it produces output different than before (that's why `label-focused-foreground` is needed in your example because otherwise the module's appearance doesn't change).

I'll have to look at this later with a clear head.

---

**Writing this down so that I don't forget**

I have found that the calls

```cpp
  m_connection.copy_area(m_pixmap, m_window, m_gcontext, 0, 0, 0, 0, m_bar.size.w, m_bar.size.h);
  m_connection.flush();
```

are somehow responsible for this. I can still reproduce this even if only these two lines run during the render cycle (and no actual rendering). Removing any of the two lines stops me from being able to reproduce it, so its not (purely) a timing issue.

What I imagine is happening is that the X events we are interested in, arrive while (or before) these two lines are executed and because of that, they somehow get discarded. No idea why that is happening because neither call should clear existing events.

Another thing that could be happening is that the events do actually arrive, we just don't realize that there are new events available. This would hint at a bug with `libuv` which is responsible for detecting new events. This would explain why you only see this in the new version but it doesn't make sense at all why these two lines of code cause this.

**Comment by rien333** [comment]
> For me, what happens is that when switching from an empty workspace to an occupied one, the xwindow module stays empty.

I have to add to add that there's indeed more xwindow title weirdness occurring, though it's not super consistent for me.  I've seen what you describe above, but also that the title doesn't update at all when switching workspaces.

**Comment by fiskhest** [comment]
I am seeing the same issue on two different setups but not exactly the same.
On one computer, I press the workspace change shortcut twice for the update to come through, no matter if going to an empty or occupied workspace.
On the second computer, it is updated immediately if the workspace is occupied, but not for empty workspaces.

On both, mouse over does not update xwindow module, but a mouse click does.

**Comment by patrick96** [comment]
I think I figured it out. I had a similar issue a few weeks ago, where for some reason polybar wasn't receiving some events from the X server.

Turns out that the way we listened for new events was slightly wrong. We were basically listening if new messages arrived on the channel, but it could happen that messages would arrive on the channel and be cached before we start listening. In that case, there would be messages ready to be processed but listening on the channel would never tell us that.
I fixed that in #2820.

I unfortunately can't reproduce the issue here with the buggy version of polybar anymore, so I'm unable to verify if it is actually fixed, but I am almost certain that it will be.

If you are still experiencing this issue, could you compile polybar from the `master` branch?

**Comment by rien333** [comment]
> If you are still experiencing this issue, could you compile polybar from the master branch?

Fixed!

Thank you so much for not forgetting about this issue :)

**Comment by patrick96** [comment]
I actually did forget ;)

I just stumbled upon it by accident and remembered that I did fix an issue with events not arriving.

**Comment by slashbeast** [comment]
@patrick96 I just hit this bug, any chance you'd do another release? Last one was in May last year, before this fix was merged.

**Comment by DrakoDom** [comment]
I'm also experiencing this issue on version 3.6.3-r2 on Gentoo.
