### ISSUE TITLE
[Bug]: (xworkspaces) urgency hint shown even when currently focused window triggers it

### ISSUE THREAD

**Issue by natrys** [polybar/polybar#2739]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

Run polybar with xworkspaces module enabled, and then in any terminal window trigger the bell:

``` sh
echo -e '\a'
```

### Minimal config

```dosini
[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
modules-left = xworkspaces

[module/xworkspaces]
type = internal/xworkspaces

label-active = %index%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %index%
label-occupied-padding = 1

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %index%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1
```

### Expected behavior

When using the `bspwm` module (e.g.), the focused window setting urgent hint to itself doesn't mean anything - at least polybar doesn't visibly react in any way, which is the intuitive behaviour.

### Actual behavior

When using the `xworkspaces` module, the focused window setting urgent hint to itself actually leads to visible reaction, e.g. label-urgent-background being shown for the focused workspace in polybar.

(This is annoying because I ring the terminal bell in my PS1 prompt, to be notified when long running shell programs finishes in unfocused workspaces. But now I am setting the urgency hint all the time in focused workspace/window)

### Window Manager and Version

bspwm-0.9.10

### Linux Distribution

Void Linux

### Polybar version

```text
(compiled from git HEAD, commit: 86f2baa5500c2f74f910286924e56584f4ef3669)

polybar 3.6.3

Features: +alsa +curl -i3 -mpd -network(wireless-tools) -pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: None
Compiler: /usr/bin/g++
Compiler flags: -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -fdebug-prefix-map=/builddir/polybar-86f2baa5500c2f74f910286924e56584f4ef3669=.  -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
I can't reproduce this at all. For me bspwm will not even update the proper window properties when the terminal bell rings (even if the terminal is on another workspace). Could you please share your bspwm config as well?

The xworkspaces module just uses the window properties when determining urgency, it is the WM's (maybe also the window's) responsibility to remove the urgency flag once the window is activated. Most likely the urgency flag is still on the window and that's why polybar is marking the workspace as urgent.

**Comment by patrick96** [comment]
I was finally able to reproduce this. Seems it only occurs in urxvt. I didn't load my `.Xresources` file for the bspwm session before, that's why `urgentOnBell` wasn't turned on.

This is not a polybar bug, the urxvt window has the urgency bit set in `WM_HINTS` (which is what polybar uses to determine workspace urgency) even if the terminal window is active while the bell rings.
I couldn't tell you whether the bug is in bspwm or urxvt, the issue seems to only occur in combination of the two though. Probably best to ask around in bspwm or urxvt help channels.

**Comment by natrys** [comment]
@patrick96 I see. However in the interim I have downgraded to polybar 3.5.7 and the issue doesn't exist there (all else being same). I want to try and bisect it, unless you think polybar is now doing right thing (and bspwm/urxvt combo being categorically wrong regardless of old behaviour) and hence it's not a regression.

**Comment by patrick96** [comment]
In 3.5.7, `label-urgent` for the xworkspaces module was still broken. The urgency was removed from a workspace on every update of the module (even if the workspace was still urgent). Since you're using bspwm, I'd recommend using the bspwm module

**Comment by natrys** [comment]
Ah okay, thanks for the heads up. Fwiw, I trying to see if I could stay within 3.6.* until #2637 was resolved. But I guess 3.5.7 + `bspwm` module would be the least headache inducing choice. I will just need to revert some my IPC scripts.
