### ISSUE TITLE
[Bug]: Brightness not updated with amdgpu_bl

### ISSUE THREAD

**Issue by vincentbernat** [polybar/polybar#2835]
### Checklist

- [X] I have read the appropriate section in the [contributing guidelines](https://github.com/polybar/polybar/blob/master/CONTRIBUTING.md)
- [X] I believe this issue is a problem with polybar itself and not a misconfiguration on my part
- [X] I have searched for other open and closed [issues](https://github.com/polybar/polybar/issues?q=is%3Aissue) that may have already reported this problem
- [X] I have checked the [known issues](https://github.com/polybar/polybar/wiki/Known-Issues) page for this problem.
- [X] I have followed the [debugging guide](https://github.com/polybar/polybar/wiki/Debugging-your-Config) to narrow down the problem to a minimal config.

### Steps to reproduce

I am using the following configuration:

```ini
[module/brightness]
type = internal/backlight
card = amdgpu_bl0
format = <ramp> <label>
label = %percentage: 2%%
ramp-0 = 
ramp-1 = 
enable-scroll = true
```

However, the value displayed is one value late. This is easy to reproduce:

```
 09:33 ❱ brightnessctl set 5%+ ; brightnessctl
Updated device 'amdgpu_bl0':
Device 'amdgpu_bl0' of class 'backlight':
        Current brightness: 26 (10%)
        Max brightness: 255

Device 'amdgpu_bl0' of class 'backlight':
        Current brightness: 26 (10%)
        Max brightness: 255
```

The value display stays to 5%. Adding a `sleep 0.1` between the two commands "fix" the issue. So, I am wondering if polybar is not eating some inotify events? With `inotifywait -m`, I am getting all the events:

```
/sys/class/backlight/amdgpu_bl0/brightness OPEN
/sys/class/backlight/amdgpu_bl0/brightness ACCESS
/sys/class/backlight/amdgpu_bl0/brightness CLOSE_NOWRITE,CLOSE
/sys/class/backlight/amdgpu_bl0/brightness OPEN
/sys/class/backlight/amdgpu_bl0/brightness ACCESS
/sys/class/backlight/amdgpu_bl0/brightness CLOSE_NOWRITE,CLOSE
/sys/class/backlight/amdgpu_bl0/brightness OPEN
/sys/class/backlight/amdgpu_bl0/brightness ACCESS
/sys/class/backlight/amdgpu_bl0/brightness CLOSE_NOWRITE,CLOSE
/sys/class/backlight/amdgpu_bl0/brightness OPEN
/sys/class/backlight/amdgpu_bl0/brightness ACCESS
/sys/class/backlight/amdgpu_bl0/brightness CLOSE_NOWRITE,CLOSE
/sys/class/backlight/amdgpu_bl0/brightness MODIFY
/sys/class/backlight/amdgpu_bl0/brightness OPEN
/sys/class/backlight/amdgpu_bl0/brightness MODIFY
/sys/class/backlight/amdgpu_bl0/brightness CLOSE_WRITE,CLOSE
/sys/class/backlight/amdgpu_bl0/brightness OPEN
/sys/class/backlight/amdgpu_bl0/brightness ACCESS
/sys/class/backlight/amdgpu_bl0/brightness CLOSE_NOWRITE,CLOSE
```

### Minimal config

```dosini
[module/brightness]
type = internal/backlight
card = amdgpu_bl0
format = <label>
label = %percentage: 2%%
```

### Expected behavior

The brightness should always be up-to-date.

### Actual behavior

The brightness is one read late.

### Window Manager and Version

i3-gaps 4.21

### Linux Distribution

Debian unstable

### Polybar version

```text
polybar 3.6.3

Features: +alsa -curl +i3 -mpd +network(libnl) +pulseaudio +xkeyboard

X extensions: +randr (+monitors) +composite +xkb +xrm +xcursor

Build type: Release
Compiler: /nix/store/j061mvdxw70xz20r2r0lr5lk0rcsjf9i-gcc-wrapper-11.3.0/bin/g++
Compiler flags:  -O3 -DNDEBUG -Wall -Wextra -Wpedantic -Wsuggest-override
Linker flags:  -Wall -Wextra -Wpedantic -Wsuggest-override  -Wall -Wextra -Wpedantic -Wsuggest-override
```

**Comment by patrick96** [comment]
Does this also happen if you set `use-actual-brightness = true`?

**Comment by vincentbernat** [comment]
It works fine with `use-actual-brightness = true`. Also, the value is correct.

```
 07:13 ❱ grep . *brightness
actual_brightness:52
brightness:52
max_brightness:255
```

This has been fixed by:

```
commit 69d9f4278d0f9d24607645f10e5ac5c59c77a4ac
Author: Alexander Monakov <amonakov@ispras.ru>
Date:   Tue Aug 4 23:13:13 2020 +0300

    drm/amd/display: use correct scale for actual_brightness

    Documentation for sysfs backlight level interface requires that
    values in both 'brightness' and 'actual_brightness' files are
    interpreted to be in range from 0 to the value given in the
    'max_brightness' file.

    With amdgpu, max_brightness gives 255, and values written by the user
    into 'brightness' are internally rescaled to a wider range. However,
    reading from 'actual_brightness' gives the raw register value without
    inverse rescaling. This causes issues for various userspace tools such
    as PowerTop and systemd that expect the value to be in the correct
    range.

    Introduce a helper to retrieve internal backlight range. Use it to
    reimplement 'convert_brightness' as 'convert_brightness_from_user' and
    introduce 'convert_brightness_to_user'.
```

Linux 5.10.

I am fine with having `use-actual-brightness = true`, but maybe the AMD check could be removed now?

**Comment by vincentbernat** [comment]
With the patch, it crashes on start:
```
                                                Stack trace of thread 293884:
                                                #0  0x00000000004d8749 _ZN7polybar7modules16backlight_module8on_eventEPNS_13inotify_eventE (.polybar-wrapped + 0xd8749)
                                                #1  0x00000000004dfd40 _ZN7polybar7modules14inotify_moduleINS0_16backlight_moduleEE6runnerEv (.polybar-wrapped + 0xdfd40)
                                                #2  0x00007f6b14adf3d4 execute_native_thread_routine (libstdc++.so.6 + 0xdf3d4)
                                                #3  0x00007f6b14688e86 start_thread (libc.so.6 + 0x88e86)
                                                #4  0x00007f6b1470fc60 __clone3 (libc.so.6 + 0x10fc60)

                                                Stack trace of thread 293883:
                                                #0  0x00007f6b146fe624 read (libc.so.6 + 0xfe624)
                                                #1  0x00007f6b14ad580f _ZNSt12__basic_fileIcE6xsgetnEPcl (libstdc++.so.6 + 0xd580f)
                                                #2  0x00007f6b14b11ee0 _ZNSt13basic_filebufIcSt11char_traitsIcEE9underflowEv (libstdc++.so.6 + 0x111ee0)
                                                #3  0x00007f6b14acd9ba _ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4_ (libstdc++.so.6 + 0xcd9ba)
                                                #4  0x0000000000527c10 _ZN7polybar7modules13memory_module6updateEv (.polybar-wrapped + 0x127c10)
                                                #5  0x000000000052db83 _ZN7polybar7modules12timer_moduleINS0_13memory_moduleEE6runnerEv (.polybar-wrapped + 0x12db83)
                                                #6  0x00007f6b14adf3d4 execute_native_thread_routine (libstdc++.so.6 + 0xdf3d4)
                                                #7  0x00007f6b14688e86 start_thread (libc.so.6 + 0x88e86)
                                                #8  0x00007f6b1470fc60 __clone3 (libc.so.6 + 0x10fc60)

                                                Stack trace of thread 293885:
                                                #0  0x00007f6b1470fc4d __clone3 (libc.so.6 + 0x10fc4d)
                                                ELF object binary architecture: AMD x86-64
```

**Comment by patrick96** [comment]
Oh, that's my bad, there was a nullpointer I didn't consider (in the newest revision this never happens anymore, but here it still does). Here is the fixed patch:
[backlight.patch.txt](https://github.com/polybar/polybar/files/9759866/backlight.patch.txt)

Hopefully it works, unfortunately I don't have a backlight in my system, so I'm not able to test the patch right now.

I appreciate you helping out here. Hopefully we can finally get some confirmation on what the underlying issue here is.

**Comment by vincentbernat** [comment]
Here is the result. First with `use-actual-brightness`, then without. I am increasing and decreasing backlight each time.

```
Oct 12 09:00:50 wally polybar[351553]: polybar|notice:  Loading module 'brightness' of type 'internal/backlight'
Oct 12 09:00:50 wally polybar[351553]: polybar|notice:  module/brightness: on_event{<no event>}
Oct 12 09:00:50 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 13.000000, percentage: 5
Oct 12 09:00:56 wally polybar[351553]: polybar|notice:  module/brightness: on_event{filename: /sys/class/backlight/amdgpu_bl0/actual_brightness, is_dir: false, wd: 1, cookie: 0, mask: 2}
Oct 12 09:00:56 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 26.000000, percentage: 10
Oct 12 09:00:57 wally polybar[351553]: polybar|notice:  module/brightness: on_event{filename: /sys/class/backlight/amdgpu_bl0/actual_brightness, is_dir: false, wd: 1, cookie: 0, mask: 2}
Oct 12 09:00:57 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 13.000000, percentage: 5
Oct 12 09:01:35 wally polybar[351553]: polybar|notice:  Loading module 'brightness' of type 'internal/backlight'
Oct 12 09:01:35 wally polybar[351553]: polybar|notice:  module/brightness: on_event{<no event>}
Oct 12 09:01:35 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 13.000000, percentage: 5
Oct 12 09:01:45 wally polybar[351553]: polybar|notice:  module/brightness: on_event{filename: /sys/class/backlight/amdgpu_bl0/brightness, is_dir: false, wd: 1, cookie: 0, mask: 49}
Oct 12 09:01:45 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 13.000000, percentage: 5
Oct 12 09:01:47 wally polybar[351553]: polybar|notice:  module/brightness: on_event{filename: /sys/class/backlight/amdgpu_bl0/brightness, is_dir: false, wd: 1, cookie: 0, mask: 49}
Oct 12 09:01:47 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 26.000000, percentage: 10
```

**Comment by patrick96** [comment]
Hmm, it certainly looks like polybar reads the wrong value from the file.

Interestingly, when using `actual_brightness`, the inotify event is triggered because `File was modified` (flag = 2), and when using `brightness`, the events are:

* `File was accessed.` (flag = 1)
* `Unwrittable file closed.` (flag = 16)
* `File was opened.` (flag = 32)

No idea why we don't get any modification events here.

---

Just one more thing I want to try, setting `use-actual-brightness = false`, increase the brightness, confirm the value in polybar lags one behind, and let polybar run for 5-10 seconds before killing it.

I expect there to be a message with the old value every second.

**Comment by vincentbernat** [comment]
By the time I got the logs from polybar, a few seconds have elapsed, so no additional events I think.

In the kernel, there is:
```c
static void backlight_generate_event(struct backlight_device *bd,
				     enum backlight_update_reason reason)
{
	char *envp[2];

	switch (reason) {
	case BACKLIGHT_UPDATE_SYSFS:
		envp[0] = "SOURCE=sysfs";
		break;
	case BACKLIGHT_UPDATE_HOTKEY:
		envp[0] = "SOURCE=hotkey";
		break;
	default:
		envp[0] = "SOURCE=unknown";
		break;
	}
	envp[1] = NULL;
	kobject_uevent_env(&bd->dev.kobj, KOBJ_CHANGE, envp);
	sysfs_notify(&bd->dev.kobj, NULL, "actual_brightness");
}
```

Nothing similar for `brightness`, so I suppose this is expected you don't get inotify events for `brightness`.

**Comment by vincentbernat** [comment]
I confirm that with `use-actual-brightness = false`, increasing the brighness logs the old value and nothing else happens:
```
Oct 12 22:38:21 wally polybar[351553]: polybar|notice:  module/brightness: on_event{filename: /sys/class/backlight/amdgpu_bl0/brightness, is_dir: false, wd: 1, cookie: 0, mask: 49}
Oct 12 22:38:21 wally polybar[351553]: polybar|notice:  module/brightness: max: 255.000000, val: 13.000000, percentage: 5
```

**Comment by patrick96** [comment]
Hmm, I think I misunderstood/misread what the code in the inotify module does. I assumed it just sent out an event every second if it didn't receive any, but that's not true. It just polls once every second for 1 second but only updates if it receives an event during that time. Otherwise it just idles for a bit and tries again.

The question now is whether it would make sense to have something like the battery module's `poll-interval` for the backlight module as well, and whether it would even help.

I have made another patch that now should update the module every second.

[backlight.patch.txt](https://github.com/polybar/polybar/files/9768752/backlight.patch.txt)

That should be the last patch I'm asking you to test out... (hopefully) :wink:

If the wrong outdated value is only read once when the event arrives, but during the next periodical update, the module reads the new correct value, then a poll-interval setting might make sense. It would reduce problems like this from "the module is always behind/never updates" to "the module updates a second or so too late".

Of course ideally everyone would be able to use the `actual_brightness` file, but that is still not possible for everyone. In particular, anyone with an amdgpu and a kernel without the fix (< 5.9) and apparently some nvidia gpus, don't produce events for `actual_backlight` at all ([reddit](https://www.reddit.com/r/Polybar/comments/xwtzp4/backlight_module_doesnt_update_when_brightness_is/)).

**Comment by vincentbernat** [comment]
I would prefer to not poll by default as each program polling prevents the CPU from sleeping and it impacts battery life. I'll test your patch once I am on my laptop.

**Comment by vincentbernat** [comment]
Your patch works, even with `use-actual-brightness` set to false.

**Comment by patrick96** [comment]
Interesting... Is the update delayed by a second or so?

This probably means that because polybar doesn't get inotify write events for the `backlight` file, the inotiy events it gets arrive before the change in value happens and thus polybar still reads the old value.

I'll whip up a PR that should have the correct behavior in all cases:

* Nothing changes when `actual_brightness` is used
* For the `brightness` file, the module updates if there hasn't been an update in the past second (configurable with `poll-interval`).

Thanks for helping me debug this, it was really helpful and also gave me a better understanding about where inotify-based modules can still be improved

**Comment by vincentbernat** [comment]
Yes, when not using actual brightness, the updated is delayed by a second.

**Comment by patrick96** [comment]
Yeah, that confirms it. When polybar gets the inotify event, the file doesn't actually have the right value yet and polybar reads the old value.
