### ISSUE TITLE
System tray icons are incorrectly drawn when org.gnome.desktop.interface scaling-factor is not 1

### ISSUE THREAD

**Issue by adamatom** [polybar/polybar#525]
If you change the org.gnome.desktop.interface scaling-factor to something other than 1 the system tray icons aren't properly drawn. The scale is off, and if the icon changes (network manager, sound icon), the icon redraws without clearing.

![gscreenshot_2017-04-09-072711](https://cloud.githubusercontent.com/assets/1854721/24836957/f2b7a414-1cf6-11e7-9297-7d07c70183ff.png)

**Comment by patrick96** [comment]
We have recently implemented a new tray that runs as a module where we rewrote a lot of the rendering code (#2609, #2689).

Some of these rendering issues may be fixed by this, but there are still some that may occur (I have been struggling to fix the dropbox icon using arbitrary images as its background data).
I am going to close this issue, if you experience rendering issues like these while using the new tray module (the old tray using `tray-position` still has the same issues), please report the application and your polybar version (`polybar -v`) together with a screenshot in #2933.
