### ISSUE TITLE
Conventions and guidelines

### ISSUE THREAD

**Issue by jaagr** [polybar/polybar#817]
As the project is growing I think it would be good to introduce some conventions and guidelines to keep everything a bit more uniform.

For example:
* Coding guidelines
* Merge strategy (e.g. `--ff-only`)
* Conventions of git messages

It's possible to add verification to travis-ci that would automate the process.

Any thoughts?

**Comment by patrick96** [comment]
I think that's a great idea.

Also I think we should make a rule that even us maintainers should only use PRs to change the codebase. Right now this is already happening for bigger features and stuff, but I think we should do this for all changes. Like this we would have a dedicated space for each change, it's easier for everyone to keep track or what's happening and why and this also allows us to group a set of changes together. This can also be used to make sure that no commit fails a travis build.

For coding guidelines it would probably be good to add a pre commit hook that automatically formats the code to conform to certain style guidelines.
I don't think having many coding rules is wise because it would add a lot of overhead for first-time contributors and it probably wouldn't help the readability of the code that much.

Can `--ff-only` be forced in a github PR or would we have to merge PRs on the command line?

**Comment by jaagr** [comment]
Yeah I totally agree about forcing pull-requests for everyone. I think that can be fixed by changing the repository settings. I will have a look.

I'm generally against applying changes automatically when performing an action (e.g. reformatting the code upon commit) but a travis check using for example `clang-format` could hint the contributor that the committed code needs to be changed.

I agree that it's not a good idea to add alot of overhead for first-timers but some restrictions is, in my opinion, needed to maintain the quality. A `clang-format` check does of course not ensure the quality of the contributed code but it's a start to keep the code uniform.

**Comment by jaagr** [comment]
I removed the ability to merge pull-requests using `--no-ff`.

**Comment by jaagr** [comment]
There's no way to block changes, done by contributors, to the default branch from what I can see in the settings. But we are still a low number of contributors so for now I guess we could agree that we create a PR for all changes. And of course we cannot merge the PR ourselves.

**Comment by patrick96** [comment]
Yeah maybe we could add a separate travis check just for `clang-format`

Just agreeing on PRs only will probably suffice. For small PRs, I think that we could allow people to merge their own PRs, if it really messes things up, it's easy to undo the whole PR at once.

While I have you here, can you add us to the xpp and i3ipcpp repos?

**Comment by jaagr** [comment]
Regarding small PR's: I still think we should have a requirement of at least 1 approval (unfortunately I don't think we can enforce it by a GitHub setting). After that you could of course merge it yourself.

Yeah, of course, I'll add you as contributors there as well.

**Comment by jaagr** [comment]
I have added all polybar contributors to the lib forks (xpp, i3icpp).

**Comment by NBonaparte** [comment]
Should we have a todo list of some kind? We could possibly create a kanban board under Projects and manage stuff there.

**Comment by patrick96** [comment]
We could also open a PR which contains those guidelines written down and we could then track everything over there. What do you think would be better?

**Comment by NBonaparte** [comment]
I've been considering using Projects as a centralized location to manage feature requests/enhancements, so we could possibly include this over there, and convert it into a PR when we're ready.

Should this be under CONTRIBUTING.md?

**Comment by patrick96** [comment]
Having feature requests in a centralized location will certainly help us keep track of them better and not let them slip through the cracks. How would discussions work in a setup like that? Can we do that inside the Project or would still need to use an issue or PR for this?


> Should this be under CONTRIBUTING.md?

What do you mean by "this"?

**Comment by NBonaparte** [comment]
From what I've seen, if a card doesn't have an issue yet, there is an option to convert it into an issue, so discussions should occur there. Existing PRs and issues can be added as-is.

By this, I mean "conventions and guidelines", as in listing all of them within CONTRIBUTING.md.

**Comment by jaagr** [comment]
I second this.
